import { Speaker } from '@/models'

/**
 * Sentinel ID used to identify the pre-made speaker.
 * This value will never collide with a real MongoDB ObjectId.
 */
export const PRE_MADE_SPEAKER_ID = 'premade'

/**
 * A virtual speaker that ships with the app. When selected, the UI
 * renders the static card sets below instead of fetching from the API.
 */
export const PRE_MADE_SPEAKER: Speaker = {
  _id: PRE_MADE_SPEAKER_ID,
  name: 'Pre-made Cards',
  parentId: '',
  villagerIds: [],
}

export function isPremadeSpeaker(speaker: Speaker | null): boolean {
  return speaker?._id === PRE_MADE_SPEAKER_ID
}

// ─── Shared card type ──────────────────────────────────────────────
export type PremadeCard = {
  _id: string
  name: string
  description?: string
  icon: string // lucide-react icon name in PascalCase
  speakerId: typeof PRE_MADE_SPEAKER_ID
}

export type PremadePlaceCard = PremadeCard & {
  address?: string
}

// Helper to create a card with a stable _id
const card = (
  category: string,
  index: number,
  name: string,
  icon: string,
  description?: string,
): PremadeCard => ({
  _id: `premade-${category}-${index}`,
  name,
  icon,
  description: description || '',
  speakerId: PRE_MADE_SPEAKER_ID,
})

const placeCard = (
  index: number,
  name: string,
  icon: string,
  description?: string,
  address?: string,
): PremadePlaceCard => ({
  ...card('places', index, name, icon, description),
  address,
})

// ─── FOODS (100 cards) ─────────────────────────────────────────────
export const PREMADE_FOODS: PremadeCard[] = [
  card('foods', 1, 'Pizza', 'Pizza', 'I want pizza'),
  card('foods', 2, 'Chicken Nuggets', 'Drumstick', 'I want chicken nuggets'),
  card('foods', 3, 'Mac and Cheese', 'Wheat', 'I want mac and cheese'),
  card('foods', 4, 'Grilled Cheese', 'Sandwich', 'I want grilled cheese'),
  card('foods', 5, 'Hot Dog', 'Beef', 'I want a hot dog'),
  card('foods', 6, 'Hamburger', 'Beef', 'I want a hamburger'),
  card('foods', 7, 'French Fries', 'Utensils', 'I want french fries'),
  card('foods', 8, 'Spaghetti', 'Utensils', 'I want spaghetti'),
  card('foods', 9, 'Tacos', 'Utensils', 'I want tacos'),
  card('foods', 10, 'Rice', 'Wheat', 'I want rice'),
  card('foods', 11, 'Soup', 'Soup', 'I want soup'),
  card('foods', 12, 'Sandwich', 'Sandwich', 'I want a sandwich'),
  card('foods', 13, 'Toast', 'Croissant', 'I want toast'),
  card('foods', 14, 'Pancakes', 'Cake', 'I want pancakes'),
  card('foods', 15, 'Waffles', 'Cake', 'I want waffles'),
  card('foods', 16, 'Cereal', 'Milk', 'I want cereal'),
  card('foods', 17, 'Oatmeal', 'Wheat', 'I want oatmeal'),
  card('foods', 18, 'Eggs', 'Egg', 'I want eggs'),
  card('foods', 19, 'Bacon', 'Beef', 'I want bacon'),
  card('foods', 20, 'Yogurt', 'CupSoda', 'I want yogurt'),
  card('foods', 21, 'Apple', 'Apple', 'I want an apple'),
  card('foods', 22, 'Banana', 'Banana', 'I want a banana'),
  card('foods', 23, 'Grapes', 'Grape', 'I want grapes'),
  card('foods', 24, 'Strawberries', 'Cherry', 'I want strawberries'),
  card('foods', 25, 'Blueberries', 'Cherry', 'I want blueberries'),
  card('foods', 26, 'Orange', 'Citrus', 'I want an orange'),
  card('foods', 27, 'Watermelon', 'Apple', 'I want watermelon'),
  card('foods', 28, 'Pineapple', 'Citrus', 'I want pineapple'),
  card('foods', 29, 'Mango', 'Citrus', 'I want mango'),
  card('foods', 30, 'Peach', 'Apple', 'I want a peach'),
  card('foods', 31, 'Carrots', 'Carrot', 'I want carrots'),
  card('foods', 32, 'Broccoli', 'Leaf', 'I want broccoli'),
  card('foods', 33, 'Corn', 'Wheat', 'I want corn'),
  card('foods', 34, 'Green Beans', 'Bean', 'I want green beans'),
  card('foods', 35, 'Peas', 'Bean', 'I want peas'),
  card('foods', 36, 'Mashed Potatoes', 'Utensils', 'I want mashed potatoes'),
  card('foods', 37, 'Sweet Potato', 'Carrot', 'I want sweet potato'),
  card('foods', 38, 'Salad', 'Salad', 'I want a salad'),
  card('foods', 39, 'Celery', 'Leaf', 'I want celery'),
  card('foods', 40, 'Cucumber', 'Salad', 'I want cucumber'),
  card('foods', 41, 'Cheese', 'Sandwich', 'I want cheese'),
  card('foods', 42, 'Crackers', 'Cookie', 'I want crackers'),
  card('foods', 43, 'Goldfish Crackers', 'Fish', 'I want goldfish crackers'),
  card('foods', 44, 'Pretzels', 'Cookie', 'I want pretzels'),
  card('foods', 45, 'Chips', 'Utensils', 'I want chips'),
  card('foods', 46, 'Popcorn', 'Popcorn', 'I want popcorn'),
  card('foods', 47, 'Trail Mix', 'Nut', 'I want trail mix'),
  card('foods', 48, 'Granola Bar', 'Wheat', 'I want a granola bar'),
  card('foods', 49, 'Fruit Snacks', 'Cherry', 'I want fruit snacks'),
  card('foods', 50, 'Applesauce', 'Apple', 'I want applesauce'),
  card('foods', 51, 'Peanut Butter', 'Nut', 'I want peanut butter'),
  card('foods', 52, 'Jelly Sandwich', 'Sandwich', 'I want a jelly sandwich'),
  card('foods', 53, 'Bagel', 'Croissant', 'I want a bagel'),
  card('foods', 54, 'Muffin', 'Cake', 'I want a muffin'),
  card('foods', 55, 'Donut', 'Cookie', 'I want a donut'),
  card('foods', 56, 'Cookie', 'Cookie', 'I want a cookie'),
  card('foods', 57, 'Brownie', 'Cake', 'I want a brownie'),
  card('foods', 58, 'Cake', 'Cake', 'I want cake'),
  card('foods', 59, 'Ice Cream', 'IceCream', 'I want ice cream'),
  card('foods', 60, 'Popsicle', 'IceCream', 'I want a popsicle'),
  card('foods', 61, 'Pudding', 'CupSoda', 'I want pudding'),
  card('foods', 62, 'Jello', 'CupSoda', 'I want jello'),
  card('foods', 63, 'Candy', 'Candy', 'I want candy'),
  card('foods', 64, 'Chocolate', 'Candy', 'I want chocolate'),
  card('foods', 65, 'Lollipop', 'Lollipop', 'I want a lollipop'),
  card('foods', 66, 'Gummy Bears', 'Candy', 'I want gummy bears'),
  card('foods', 67, 'Water', 'GlassWater', 'I want water'),
  card('foods', 68, 'Milk', 'Milk', 'I want milk'),
  card('foods', 69, 'Chocolate Milk', 'Milk', 'I want chocolate milk'),
  card('foods', 70, 'Juice', 'CupSoda', 'I want juice'),
  card('foods', 71, 'Apple Juice', 'Apple', 'I want apple juice'),
  card('foods', 72, 'Orange Juice', 'Citrus', 'I want orange juice'),
  card('foods', 73, 'Lemonade', 'Citrus', 'I want lemonade'),
  card('foods', 74, 'Smoothie', 'CupSoda', 'I want a smoothie'),
  card('foods', 75, 'Hot Chocolate', 'Coffee', 'I want hot chocolate'),
  card('foods', 76, 'Chicken Soup', 'Soup', 'I want chicken soup'),
  card('foods', 77, 'Tomato Soup', 'Soup', 'I want tomato soup'),
  card('foods', 78, 'Fish Sticks', 'Fish', 'I want fish sticks'),
  card('foods', 79, 'Shrimp', 'Fish', 'I want shrimp'),
  card('foods', 80, 'Steak', 'Beef', 'I want steak'),
  card('foods', 81, 'Chicken Breast', 'Drumstick', 'I want chicken'),
  card('foods', 82, 'Turkey', 'Drumstick', 'I want turkey'),
  card('foods', 83, 'Ham', 'Beef', 'I want ham'),
  card('foods', 84, 'Meatballs', 'Beef', 'I want meatballs'),
  card('foods', 85, 'Burrito', 'Utensils', 'I want a burrito'),
  card('foods', 86, 'Quesadilla', 'Utensils', 'I want a quesadilla'),
  card('foods', 87, 'Nachos', 'Utensils', 'I want nachos'),
  card('foods', 88, 'Fried Rice', 'Wheat', 'I want fried rice'),
  card('foods', 89, 'Noodles', 'Utensils', 'I want noodles'),
  card('foods', 90, 'Ramen', 'Soup', 'I want ramen'),
  card('foods', 91, 'Bread', 'Croissant', 'I want bread'),
  card('foods', 92, 'Butter', 'Sandwich', 'I want butter'),
  card('foods', 93, 'Jam', 'Cherry', 'I want jam'),
  card('foods', 94, 'Honey', 'Flower', 'I want honey'),
  card('foods', 95, 'Ketchup', 'CupSoda', 'I want ketchup'),
  card('foods', 96, 'Ranch', 'CupSoda', 'I want ranch'),
  card('foods', 97, 'Syrup', 'CupSoda', 'I want syrup'),
  card('foods', 98, 'Raisins', 'Grape', 'I want raisins'),
  card('foods', 99, 'Dried Fruit', 'Cherry', 'I want dried fruit'),
  card('foods', 100, 'String Cheese', 'Sandwich', 'I want string cheese'),
]

// ─── ACTIVITIES (100 cards) ────────────────────────────────────────
export const PREMADE_ACTIVITIES: PremadeCard[] = [
  card('activities', 1, 'Watch TV', 'Tv', 'I want to watch TV'),
  card(
    'activities',
    2,
    'Watch a Movie',
    'Clapperboard',
    'I want to watch a movie',
  ),
  card(
    'activities',
    3,
    'Play Video Games',
    'Gamepad',
    'I want to play video games',
  ),
  card(
    'activities',
    4,
    'Play on Tablet',
    'Computer',
    'I want to use the tablet',
  ),
  card(
    'activities',
    5,
    'Listen to Music',
    'Music',
    'I want to listen to music',
  ),
  card('activities', 6, 'Sing a Song', 'Mic', 'I want to sing'),
  card('activities', 7, 'Dance', 'Music', 'I want to dance'),
  card('activities', 8, 'Read a Book', 'Book', 'I want to read a book'),
  card('activities', 9, 'Draw', 'Pen', 'I want to draw'),
  card('activities', 10, 'Color', 'Palette', 'I want to color'),
  card('activities', 11, 'Paint', 'Paintbrush', 'I want to paint'),
  card(
    'activities',
    12,
    'Play with Clay',
    'Blocks',
    'I want to play with clay',
  ),
  card('activities', 13, 'Do a Puzzle', 'Puzzle', 'I want to do a puzzle'),
  card(
    'activities',
    14,
    'Build with Legos',
    'Blocks',
    'I want to build with Legos',
  ),
  card(
    'activities',
    15,
    'Build with Blocks',
    'Blocks',
    'I want to build with blocks',
  ),
  card(
    'activities',
    16,
    'Play with Trains',
    'Train',
    'I want to play with trains',
  ),
  card('activities', 17, 'Play with Cars', 'Car', 'I want to play with cars'),
  card(
    'activities',
    18,
    'Play with Dolls',
    'Heart',
    'I want to play with dolls',
  ),
  card(
    'activities',
    19,
    'Play with Action Figures',
    'Star',
    'I want to play with action figures',
  ),
  card('activities', 20, 'Play Pretend', 'Drama', 'I want to play pretend'),
  card('activities', 21, 'Play Outside', 'Sun', 'I want to play outside'),
  card(
    'activities',
    22,
    'Go to the Playground',
    'FerrisWheel',
    'I want to go to the playground',
  ),
  card('activities', 23, 'Swing', 'FerrisWheel', 'I want to swing'),
  card('activities', 24, 'Slide', 'FerrisWheel', 'I want to go on the slide'),
  card('activities', 25, 'Climb', 'Mountain', 'I want to climb'),
  card(
    'activities',
    26,
    'Jump on Trampoline',
    'Zap',
    'I want to jump on the trampoline',
  ),
  card('activities', 27, 'Ride a Bike', 'Bike', 'I want to ride my bike'),
  card('activities', 28, 'Ride a Scooter', 'Bike', 'I want to ride my scooter'),
  card(
    'activities',
    29,
    'Go for a Walk',
    'Footprints',
    'I want to go for a walk',
  ),
  card(
    'activities',
    30,
    'Go for a Run',
    'Footprints',
    'I want to go for a run',
  ),
  card('activities', 31, 'Play Catch', 'Volleyball', 'I want to play catch'),
  card('activities', 32, 'Kick a Ball', 'Volleyball', 'I want to kick a ball'),
  card(
    'activities',
    33,
    'Play Basketball',
    'Basketball',
    'I want to play basketball',
  ),
  card('activities', 34, 'Play Soccer', 'Volleyball', 'I want to play soccer'),
  card('activities', 35, 'Play Baseball', 'Trophy', 'I want to play baseball'),
  card('activities', 36, 'Go Swimming', 'Waves', 'I want to go swimming'),
  card(
    'activities',
    37,
    'Play in the Water',
    'Waves',
    'I want to play in the water',
  ),
  card('activities', 38, 'Take a Bath', 'Bath', 'I want to take a bath'),
  card('activities', 39, 'Blow Bubbles', 'Sparkles', 'I want to blow bubbles'),
  card('activities', 40, 'Play with Sand', 'Sun', 'I want to play with sand'),
  card('activities', 41, 'Fly a Kite', 'Wind', 'I want to fly a kite'),
  card('activities', 42, 'Go Camping', 'Tent', 'I want to go camping'),
  card(
    'activities',
    43,
    'Have a Picnic',
    'Utensils',
    'I want to have a picnic',
  ),
  card('activities', 44, 'Go Fishing', 'Fish', 'I want to go fishing'),
  card('activities', 45, 'Garden', 'Flower', 'I want to garden'),
  card(
    'activities',
    46,
    'Water the Plants',
    'Sprout',
    'I want to water the plants',
  ),
  card('activities', 47, 'Cook', 'Utensils', 'I want to help cook'),
  card('activities', 48, 'Bake', 'Cake', 'I want to bake'),
  card('activities', 49, 'Make a Snack', 'Cookie', 'I want to make a snack'),
  card(
    'activities',
    50,
    'Set the Table',
    'Utensils',
    'I want to set the table',
  ),
  card('activities', 51, 'Do Crafts', 'Scissors', 'I want to do crafts'),
  card('activities', 52, 'Make Jewelry', 'Gem', 'I want to make jewelry'),
  card(
    'activities',
    53,
    'Play with Stickers',
    'Star',
    'I want to play with stickers',
  ),
  card('activities', 54, 'Make a Card', 'Heart', 'I want to make a card'),
  card(
    'activities',
    55,
    'Play Board Games',
    'Dice',
    'I want to play a board game',
  ),
  card(
    'activities',
    56,
    'Play Card Games',
    'Dice',
    'I want to play card games',
  ),
  card(
    'activities',
    57,
    'Do a Science Experiment',
    'Atom',
    'I want to do a science experiment',
  ),
  card(
    'activities',
    58,
    'Look Through a Telescope',
    'Telescope',
    'I want to look at the stars',
  ),
  card(
    'activities',
    59,
    'Use a Magnifying Glass',
    'Search',
    'I want to explore',
  ),
  card(
    'activities',
    60,
    'Play with Magnets',
    'Magnet',
    'I want to play with magnets',
  ),
  card(
    'activities',
    61,
    'Play with Slime',
    'Sparkles',
    'I want to play with slime',
  ),
  card(
    'activities',
    62,
    'Play with Play-Doh',
    'Palette',
    'I want to play with Play-Doh',
  ),
  card(
    'activities',
    63,
    'Have a Playdate',
    'Users',
    'I want to have a playdate',
  ),
  card('activities', 64, 'Visit a Friend', 'Heart', 'I want to visit a friend'),
  card(
    'activities',
    65,
    'Talk on the Phone',
    'Phone',
    'I want to talk on the phone',
  ),
  card(
    'activities',
    66,
    'Video Call',
    'Camera',
    'I want to video call someone',
  ),
  card('activities', 67, 'Take Photos', 'Camera', 'I want to take photos'),
  card('activities', 68, 'Play Dress Up', 'Shirt', 'I want to play dress up'),
  card(
    'activities',
    69,
    'Play with Puppets',
    'Drama',
    'I want to play with puppets',
  ),
  card('activities', 70, 'Tell Stories', 'Book', 'I want to tell a story'),
  card(
    'activities',
    71,
    'Listen to a Story',
    'Headphones',
    'I want to hear a story',
  ),
  card('activities', 72, 'Do Homework', 'Pencil', 'I want to do homework'),
  card(
    'activities',
    73,
    'Practice Writing',
    'Pencil',
    'I want to practice writing',
  ),
  card('activities', 74, 'Practice Math', 'Calculator', 'I want to do math'),
  card('activities', 75, 'Learn Something New', 'Lightbulb', 'I want to learn'),
  card(
    'activities',
    76,
    'Play an Instrument',
    'Piano',
    'I want to play an instrument',
  ),
  card('activities', 77, 'Play Drums', 'Drum', 'I want to play drums'),
  card('activities', 78, 'Play Guitar', 'Guitar', 'I want to play guitar'),
  card('activities', 79, 'Exercise', 'Dumbbell', 'I want to exercise'),
  card('activities', 80, 'Do Yoga', 'Heart', 'I want to do yoga'),
  card('activities', 81, 'Stretch', 'Dumbbell', 'I want to stretch'),
  card('activities', 82, 'Play Tag', 'Zap', 'I want to play tag'),
  card(
    'activities',
    83,
    'Play Hide and Seek',
    'Eye',
    'I want to play hide and seek',
  ),
  card('activities', 84, 'Race', 'Zap', 'I want to race'),
  card('activities', 85, 'Hula Hoop', 'CirclePlay', 'I want to hula hoop'),
  card('activities', 86, 'Jump Rope', 'Zap', 'I want to jump rope'),
  card(
    'activities',
    87,
    'Ride in the Car',
    'Car',
    'I want to go for a car ride',
  ),
  card(
    'activities',
    88,
    'Go on an Adventure',
    'Compass',
    'I want to go on an adventure',
  ),
  card('activities', 89, 'Explore Nature', 'Leaf', 'I want to explore nature'),
  card(
    'activities',
    90,
    'Watch Animals',
    'PawPrint',
    'I want to watch animals',
  ),
  card(
    'activities',
    91,
    'Pet an Animal',
    'PawPrint',
    'I want to pet an animal',
  ),
  card('activities', 92, 'Feed the Fish', 'Fish', 'I want to feed the fish'),
  card(
    'activities',
    93,
    'Play with the Dog',
    'Dog',
    'I want to play with the dog',
  ),
  card(
    'activities',
    94,
    'Play with the Cat',
    'Cat',
    'I want to play with the cat',
  ),
  card('activities', 95, 'Build a Fort', 'Castle', 'I want to build a fort'),
  card(
    'activities',
    96,
    'Have a Tea Party',
    'Coffee',
    'I want to have a tea party',
  ),
  card(
    'activities',
    97,
    'Play in the Snow',
    'Snowflake',
    'I want to play in the snow',
  ),
  card(
    'activities',
    98,
    'Build a Snowman',
    'Snowflake',
    'I want to build a snowman',
  ),
  card(
    'activities',
    99,
    'Play in the Rain',
    'CloudRain',
    'I want to play in the rain',
  ),
  card('activities', 100, 'Relax', 'Sofa', 'I want to relax'),
]

// ─── PLACES (100 cards) ────────────────────────────────────────────
export const PREMADE_PLACES: PremadePlaceCard[] = [
  placeCard(1, 'Home', 'Home', 'I want to go home'),
  placeCard(2, 'School', 'School', 'I want to go to school'),
  placeCard(3, "Grandma's House", 'Home', "I want to go to grandma's"),
  placeCard(4, "Grandpa's House", 'Home', "I want to go to grandpa's"),
  placeCard(5, "Mom's House", 'Home', "I want to go to mom's house"),
  placeCard(6, "Dad's House", 'Home', "I want to go to dad's house"),
  placeCard(7, "Friend's House", 'Home', "I want to go to my friend's house"),
  placeCard(8, 'Park', 'Tree', 'I want to go to the park'),
  placeCard(9, 'Playground', 'FerrisWheel', 'I want to go to the playground'),
  placeCard(10, 'Library', 'Library', 'I want to go to the library'),
  placeCard(
    11,
    'Grocery Store',
    'ShoppingCart',
    'I want to go to the grocery store',
  ),
  placeCard(12, 'Mall', 'Store', 'I want to go to the mall'),
  placeCard(13, 'Toy Store', 'Blocks', 'I want to go to the toy store'),
  placeCard(14, 'Bookstore', 'Book', 'I want to go to the bookstore'),
  placeCard(15, 'Pet Store', 'PawPrint', 'I want to go to the pet store'),
  placeCard(16, 'Restaurant', 'Utensils', 'I want to go to a restaurant'),
  placeCard(17, 'Fast Food', 'Pizza', 'I want to go get fast food'),
  placeCard(18, 'Ice Cream Shop', 'IceCream', 'I want to go get ice cream'),
  placeCard(19, 'Bakery', 'Croissant', 'I want to go to the bakery'),
  placeCard(20, 'Coffee Shop', 'Coffee', 'I want to go to the coffee shop'),
  placeCard(21, 'Pizza Place', 'Pizza', 'I want to go get pizza'),
  placeCard(22, "Doctor's Office", 'Stethoscope', 'I need to go to the doctor'),
  placeCard(23, 'Dentist', 'Smile', 'I need to go to the dentist'),
  placeCard(24, 'Hospital', 'Hospital', 'I need to go to the hospital'),
  placeCard(25, 'Pharmacy', 'Pill', 'I need to go to the pharmacy'),
  placeCard(26, 'Church', 'Church', 'I want to go to church'),
  placeCard(27, 'Movie Theater', 'Clapperboard', 'I want to go to the movies'),
  placeCard(28, 'Arcade', 'Gamepad', 'I want to go to the arcade'),
  placeCard(29, 'Bowling Alley', 'Trophy', 'I want to go bowling'),
  placeCard(30, 'Swimming Pool', 'Waves', 'I want to go to the pool'),
  placeCard(31, 'Beach', 'Sun', 'I want to go to the beach'),
  placeCard(32, 'Lake', 'Waves', 'I want to go to the lake'),
  placeCard(33, 'River', 'Waves', 'I want to go to the river'),
  placeCard(34, 'Zoo', 'PawPrint', 'I want to go to the zoo'),
  placeCard(35, 'Aquarium', 'Fish', 'I want to go to the aquarium'),
  placeCard(36, 'Museum', 'Landmark', 'I want to go to the museum'),
  placeCard(
    37,
    'Amusement Park',
    'RollerCoaster',
    'I want to go to the amusement park',
  ),
  placeCard(38, 'Water Park', 'Waves', 'I want to go to the water park'),
  placeCard(
    39,
    'Trampoline Park',
    'Zap',
    'I want to go to the trampoline park',
  ),
  placeCard(40, 'Skating Rink', 'Snowflake', 'I want to go skating'),
  placeCard(41, 'Gym', 'Dumbbell', 'I want to go to the gym'),
  placeCard(42, 'Dance Studio', 'Music', 'I want to go to dance class'),
  placeCard(43, 'Music Class', 'Piano', 'I want to go to music class'),
  placeCard(44, 'Art Class', 'Palette', 'I want to go to art class'),
  placeCard(45, 'Karate', 'Medal', 'I want to go to karate'),
  placeCard(
    46,
    'Soccer Field',
    'Volleyball',
    'I want to go to the soccer field',
  ),
  placeCard(
    47,
    'Baseball Field',
    'Trophy',
    'I want to go to the baseball field',
  ),
  placeCard(
    48,
    'Basketball Court',
    'Basketball',
    'I want to go play basketball',
  ),
  placeCard(49, 'Tennis Court', 'Trophy', 'I want to play tennis'),
  placeCard(
    50,
    'Football Field',
    'Trophy',
    'I want to go to the football field',
  ),
  placeCard(51, 'Skate Park', 'Bike', 'I want to go to the skate park'),
  placeCard(52, 'Dog Park', 'Dog', 'I want to go to the dog park'),
  placeCard(53, 'Farm', 'Tractor', 'I want to go to the farm'),
  placeCard(54, 'Garden', 'Flower', 'I want to go to the garden'),
  placeCard(55, 'Forest', 'Tree', 'I want to go to the forest'),
  placeCard(56, 'Mountain', 'Mountain', 'I want to go to the mountain'),
  placeCard(57, 'Camping', 'Tent', 'I want to go camping'),
  placeCard(58, 'Hiking Trail', 'Mountain', 'I want to go hiking'),
  placeCard(59, 'Bike Path', 'Bike', 'I want to go on the bike path'),
  placeCard(60, 'Nature Center', 'Leaf', 'I want to go to the nature center'),
  placeCard(61, 'Clothing Store', 'Shirt', 'I want to go clothes shopping'),
  placeCard(62, 'Shoe Store', 'ShoppingBag', 'I want to go buy shoes'),
  placeCard(63, 'Dollar Store', 'Coins', 'I want to go to the dollar store'),
  placeCard(
    64,
    'Hardware Store',
    'Hammer',
    'I want to go to the hardware store',
  ),
  placeCard(65, 'Gas Station', 'Car', 'We need to get gas'),
  placeCard(66, 'Car Wash', 'Car', 'I want to go to the car wash'),
  placeCard(67, 'Bank', 'PiggyBank', 'I want to go to the bank'),
  placeCard(68, 'Post Office', 'Flag', 'I want to go to the post office'),
  placeCard(69, 'Fire Station', 'Flame', 'I want to see the fire station'),
  placeCard(70, 'Police Station', 'Siren', 'I want to see the police station'),
  placeCard(71, 'Airport', 'Plane', 'I want to go to the airport'),
  placeCard(72, 'Train Station', 'Train', 'I want to go to the train station'),
  placeCard(73, 'Bus Stop', 'Bus', 'I want to go to the bus stop'),
  placeCard(74, 'Barber Shop', 'Scissors', 'I need a haircut'),
  placeCard(75, 'Laundromat', 'Shirt', 'I want to go do laundry'),
  placeCard(76, 'Therapy', 'Heart', 'I want to go to therapy'),
  placeCard(77, 'Speech Therapy', 'Mic', 'I want to go to speech therapy'),
  placeCard(78, 'Occupational Therapy', 'Hand', 'I want to go to OT'),
  placeCard(79, "Relative's House", 'Home', 'I want to visit family'),
  placeCard(80, "Neighbor's House", 'Home', "I want to go to the neighbor's"),
  placeCard(81, 'Birthday Party', 'PartyPopper', 'I want to go to a party'),
  placeCard(82, 'Sleepover', 'Moon', 'I want to go to a sleepover'),
  placeCard(
    83,
    'Playground by School',
    'FerrisWheel',
    'I want to play at the school playground',
  ),
  placeCard(84, 'Sports Practice', 'Dumbbell', 'I want to go to practice'),
  placeCard(85, 'Tutoring', 'GraduationCap', 'I want to go to tutoring'),
  placeCard(86, 'Sunday School', 'Book', 'I want to go to Sunday school'),
  placeCard(87, 'Daycare', 'Baby', 'I need to go to daycare'),
  placeCard(
    88,
    'After School Program',
    'Clock',
    'I want to go to after school',
  ),
  placeCard(89, 'Summer Camp', 'Tent', 'I want to go to camp'),
  placeCard(90, 'Vacation', 'Plane', 'I want to go on vacation'),
  placeCard(91, 'Hotel', 'Hotel', 'We are staying at a hotel'),
  placeCard(92, 'Cabin', 'Home', 'I want to go to the cabin'),
  placeCard(93, 'Waterfall', 'Waves', 'I want to see a waterfall'),
  placeCard(94, 'Botanical Garden', 'Flower', 'I want to see the gardens'),
  placeCard(95, 'Science Center', 'Atom', 'I want to go to the science center'),
  placeCard(96, 'Planetarium', 'Star', 'I want to go to the planetarium'),
  placeCard(97, 'Concert', 'Music', 'I want to go to a concert'),
  placeCard(98, 'Fair', 'FerrisWheel', 'I want to go to the fair'),
  placeCard(99, 'Parade', 'Flag', 'I want to see the parade'),
  placeCard(
    100,
    'Farmers Market',
    'Apple',
    'I want to go to the farmers market',
  ),
]

// ─── PEOPLE (100 cards) ────────────────────────────────────────────
export const PREMADE_PEOPLE: PremadeCard[] = [
  card('people', 1, 'Mom', 'Heart', 'I want to see Mom'),
  card('people', 2, 'Dad', 'Heart', 'I want to see Dad'),
  card('people', 3, 'Brother', 'User', 'I want to see my brother'),
  card('people', 4, 'Sister', 'User', 'I want to see my sister'),
  card('people', 5, 'Grandma', 'Heart', 'I want to see Grandma'),
  card('people', 6, 'Grandpa', 'Heart', 'I want to see Grandpa'),
  card('people', 7, 'Aunt', 'User', 'I want to see my aunt'),
  card('people', 8, 'Uncle', 'User', 'I want to see my uncle'),
  card('people', 9, 'Cousin', 'User', 'I want to see my cousin'),
  card('people', 10, 'Baby', 'Baby', 'I want to see the baby'),
  card(
    'people',
    11,
    'Best Friend',
    'HeartHandshake',
    'I want to see my best friend',
  ),
  card('people', 12, 'Friend', 'Users', 'I want to see my friend'),
  card('people', 13, 'Neighbor', 'Home', 'I want to see the neighbor'),
  card('people', 14, 'Teacher', 'GraduationCap', 'I want to see my teacher'),
  card('people', 15, 'Principal', 'School', 'I want to see the principal'),
  card(
    'people',
    16,
    'School Counselor',
    'Heart',
    'I want to see the counselor',
  ),
  card('people', 17, 'Bus Driver', 'Bus', 'I want to see the bus driver'),
  card('people', 18, 'Therapist', 'Heart', 'I want to see my therapist'),
  card(
    'people',
    19,
    'Speech Therapist',
    'Mic',
    'I want to see my speech therapist',
  ),
  card('people', 20, 'Doctor', 'Stethoscope', 'I want to see the doctor'),
  card('people', 21, 'Dentist', 'Smile', 'I want to see the dentist'),
  card('people', 22, 'Nurse', 'Stethoscope', 'I want to see the nurse'),
  card('people', 23, 'Coach', 'Trophy', 'I want to see my coach'),
  card(
    'people',
    24,
    'Music Teacher',
    'Music',
    'I want to see my music teacher',
  ),
  card('people', 25, 'Art Teacher', 'Palette', 'I want to see my art teacher'),
  card('people', 26, 'Librarian', 'Library', 'I want to see the librarian'),
  card('people', 27, 'Babysitter', 'Heart', 'I want to see the babysitter'),
  card('people', 28, 'Nanny', 'Heart', 'I want to see my nanny'),
  card('people', 29, 'Tutor', 'Book', 'I want to see my tutor'),
  card('people', 30, 'Pastor', 'Church', 'I want to see the pastor'),
  card(
    'people',
    31,
    'Sunday School Teacher',
    'Book',
    'I want to see my Sunday school teacher',
  ),
  card('people', 32, 'Aide', 'HandHelping', 'I want to see my aide'),
  card(
    'people',
    33,
    'Classroom Helper',
    'HandHelping',
    'I want to see the helper',
  ),
  card('people', 34, 'Pet', 'PawPrint', 'I want to see my pet'),
  card('people', 35, 'Dog', 'Dog', 'I want to see the dog'),
  card('people', 36, 'Cat', 'Cat', 'I want to see the cat'),
  card('people', 37, 'Classmate', 'Users', 'I want to see my classmate'),
  card('people', 38, 'Teammate', 'Users', 'I want to see my teammate'),
  card('people', 39, 'Pen Pal', 'Pen', 'I want to write to my pen pal'),
  card('people', 40, 'Godparent', 'Heart', 'I want to see my godparent'),
  card('people', 41, 'Step-Mom', 'Heart', 'I want to see my step-mom'),
  card('people', 42, 'Step-Dad', 'Heart', 'I want to see my step-dad'),
  card('people', 43, 'Step-Brother', 'User', 'I want to see my step-brother'),
  card('people', 44, 'Step-Sister', 'User', 'I want to see my step-sister'),
  card('people', 45, 'Half-Brother', 'User', 'I want to see my half-brother'),
  card('people', 46, 'Half-Sister', 'User', 'I want to see my half-sister'),
  card('people', 47, 'Great Grandma', 'Heart', 'I want to see great grandma'),
  card('people', 48, 'Great Grandpa', 'Heart', 'I want to see great grandpa'),
  card(
    'people',
    49,
    'Foster Parent',
    'Heart',
    'I want to see my foster parent',
  ),
  card(
    'people',
    50,
    'Social Worker',
    'Clipboard',
    'I want to see my social worker',
  ),
  card('people', 51, 'Occupational Therapist', 'Hand', 'I want to see my OT'),
  card('people', 52, 'Physical Therapist', 'Dumbbell', 'I want to see my PT'),
  card('people', 53, 'Psychologist', 'Brain', 'I want to see my psychologist'),
  card('people', 54, 'Eye Doctor', 'Eye', 'I want to see the eye doctor'),
  card('people', 55, 'Ear Doctor', 'Ear', 'I want to see the ear doctor'),
  card('people', 56, 'Pharmacist', 'Pill', 'I want to see the pharmacist'),
  card('people', 57, 'Firefighter', 'Flame', 'I want to see a firefighter'),
  card(
    'people',
    58,
    'Police Officer',
    'Siren',
    'I want to see a police officer',
  ),
  card('people', 59, 'Mail Carrier', 'Flag', 'I want to see the mail carrier'),
  card(
    'people',
    60,
    'Crossing Guard',
    'Hand',
    'I want to see the crossing guard',
  ),
  card('people', 61, 'Lunch Lady', 'Utensils', 'I want to see the lunch lady'),
  card('people', 62, 'Janitor', 'Wrench', 'I want to see the janitor'),
  card(
    'people',
    63,
    'School Secretary',
    'Clipboard',
    'I want to see the school secretary',
  ),
  card(
    'people',
    64,
    'Camp Counselor',
    'Tent',
    'I want to see my camp counselor',
  ),
  card(
    'people',
    65,
    'Swim Instructor',
    'Waves',
    'I want to see my swim teacher',
  ),
  card(
    'people',
    66,
    'Dance Teacher',
    'Music',
    'I want to see my dance teacher',
  ),
  card(
    'people',
    67,
    'Karate Teacher',
    'Medal',
    'I want to see my karate teacher',
  ),
  card(
    'people',
    68,
    'Guitar Teacher',
    'Guitar',
    'I want to see my guitar teacher',
  ),
  card(
    'people',
    69,
    'Piano Teacher',
    'Piano',
    'I want to see my piano teacher',
  ),
  card('people', 70, 'Drum Teacher', 'Drum', 'I want to see my drum teacher'),
  card(
    'people',
    71,
    'Riding Instructor',
    'PawPrint',
    'I want to see my riding teacher',
  ),
  card('people', 72, 'Scout Leader', 'Flag', 'I want to see my scout leader'),
  card('people', 73, 'Volunteer', 'HandHelping', 'I want to see the volunteer'),
  card(
    'people',
    74,
    'Big Brother/Sister',
    'HeartHandshake',
    'I want to see my big buddy',
  ),
  card('people', 75, 'Mentor', 'Star', 'I want to see my mentor'),
  card('people', 76, 'New Friend', 'Sparkles', 'I met a new friend'),
  card('people', 77, 'Old Friend', 'Heart', 'I miss my old friend'),
  card('people', 78, 'Playdate Friend', 'Users', 'I want to have a playdate'),
  card(
    'people',
    79,
    'Church Friend',
    'Church',
    'I want to see my church friend',
  ),
  card(
    'people',
    80,
    'Sport Friend',
    'Trophy',
    'I want to see my sports friend',
  ),
  card(
    'people',
    81,
    'School Friend',
    'School',
    'I want to see my school friend',
  ),
  card(
    'people',
    82,
    'Neighbor Kid',
    'Home',
    'I want to play with the neighbor kid',
  ),
  card(
    'people',
    83,
    'Family Friend',
    'Users',
    'I want to see our family friends',
  ),
  card('people', 84, 'Older Sibling', 'User', 'I want to see my older sibling'),
  card(
    'people',
    85,
    'Younger Sibling',
    'Baby',
    'I want to see my younger sibling',
  ),
  card('people', 86, 'Twin', 'Users', 'I want to see my twin'),
  card('people', 87, 'Niece', 'User', 'I want to see my niece'),
  card('people', 88, 'Nephew', 'User', 'I want to see my nephew'),
  card('people', 89, 'Family', 'Users', 'I want to see my family'),
  card('people', 90, 'Everyone', 'Users', 'I want to see everyone'),
  card('people', 91, 'No One', 'User', 'I want to be alone'),
  card('people', 92, 'Someone New', 'Sparkles', 'I want to meet someone new'),
  card('people', 93, 'Helper', 'HandHelping', 'I need a helper'),
  card('people', 94, 'Grown-Up', 'User', 'I need a grown-up'),
  card('people', 95, 'Kid', 'User', 'I want to play with a kid'),
  card('people', 96, 'Girl', 'User', 'I want to see a girl'),
  card('people', 97, 'Boy', 'User', 'I want to see a boy'),
  card('people', 98, 'Group', 'Users', 'I want to be in a group'),
  card('people', 99, 'Nobody', 'User', 'I do not want to see anyone'),
  card('people', 100, 'Myself', 'Smile', 'I want time for me'),
]

// ─── VOCABULARY WORDS (100 cards) ──────────────────────────────────
export const PREMADE_VOCAB_WORDS: PremadeCard[] = [
  // Basic needs & feelings
  card('vocab', 1, 'Yes', 'ThumbsUp', 'Yes'),
  card('vocab', 2, 'No', 'ThumbsDown', 'No'),
  card('vocab', 3, 'Please', 'HandHelping', 'Please'),
  card('vocab', 4, 'Thank You', 'Heart', 'Thank you'),
  card('vocab', 5, 'Sorry', 'Frown', 'I am sorry'),
  card('vocab', 6, 'Help', 'HandHelping', 'I need help'),
  card('vocab', 7, 'More', 'PlusIcon', 'I want more'),
  card('vocab', 8, 'All Done', 'CircleCheck', 'I am all done'),
  card('vocab', 9, 'Stop', 'Hand', 'Stop'),
  card('vocab', 10, 'Go', 'Zap', 'Go'),
  card('vocab', 11, 'Wait', 'Clock', 'Wait'),
  card('vocab', 12, 'My Turn', 'User', 'It is my turn'),
  card('vocab', 13, 'Your Turn', 'Users', 'It is your turn'),
  card('vocab', 14, 'I Want', 'Star', 'I want something'),
  card('vocab', 15, 'I Need', 'Star', 'I need something'),
  card('vocab', 16, 'I Like', 'ThumbsUp', 'I like that'),
  card('vocab', 17, "I Don't Like", 'ThumbsDown', 'I do not like that'),
  card('vocab', 18, 'I Love', 'Heart', 'I love that'),

  // Emotions
  card('vocab', 19, 'Happy', 'Smile', 'I feel happy'),
  card('vocab', 20, 'Sad', 'Frown', 'I feel sad'),
  card('vocab', 21, 'Angry', 'Angry', 'I feel angry'),
  card('vocab', 22, 'Scared', 'Eye', 'I feel scared'),
  card('vocab', 23, 'Worried', 'Meh', 'I feel worried'),
  card('vocab', 24, 'Tired', 'Moon', 'I feel tired'),
  card('vocab', 25, 'Sick', 'Thermometer', 'I feel sick'),
  card('vocab', 26, 'Hungry', 'Utensils', 'I am hungry'),
  card('vocab', 27, 'Thirsty', 'GlassWater', 'I am thirsty'),
  card('vocab', 28, 'Hot', 'Sun', 'I am hot'),
  card('vocab', 29, 'Cold', 'Snowflake', 'I am cold'),
  card('vocab', 30, 'Hurt', 'Syringe', 'Something hurts'),
  card('vocab', 31, 'Frustrated', 'Annoyed', 'I feel frustrated'),
  card('vocab', 32, 'Excited', 'Sparkles', 'I am excited'),
  card('vocab', 33, 'Bored', 'Meh', 'I am bored'),
  card('vocab', 34, 'Confused', 'CircleHelp', 'I am confused'),
  card('vocab', 35, 'Proud', 'Medal', 'I feel proud'),
  card('vocab', 36, 'Surprised', 'Sparkles', 'I am surprised'),
  card('vocab', 37, 'Calm', 'Leaf', 'I feel calm'),
  card('vocab', 38, 'Nervous', 'Zap', 'I feel nervous'),
  card('vocab', 39, 'Silly', 'Laugh', 'I feel silly'),
  card('vocab', 40, 'Loved', 'Heart', 'I feel loved'),

  // Physical needs
  card('vocab', 41, 'Bathroom', 'Bath', 'I need the bathroom'),
  card('vocab', 42, 'Drink', 'GlassWater', 'I want a drink'),
  card('vocab', 43, 'Eat', 'Utensils', 'I want to eat'),
  card('vocab', 44, 'Sleep', 'Moon', 'I want to sleep'),
  card('vocab', 45, 'Rest', 'Bed', 'I need to rest'),
  card('vocab', 46, 'Medicine', 'Pill', 'I need medicine'),
  card('vocab', 47, 'Hug', 'Heart', 'I want a hug'),
  card('vocab', 48, 'Break', 'Clock', 'I need a break'),
  card('vocab', 49, 'Outside', 'Sun', 'I want to go outside'),
  card('vocab', 50, 'Inside', 'Home', 'I want to go inside'),

  // Descriptors & directions
  card('vocab', 51, 'Big', 'Blocks', 'Big'),
  card('vocab', 52, 'Small', 'Blocks', 'Small'),
  card('vocab', 53, 'Up', 'Mountain', 'Up'),
  card('vocab', 54, 'Down', 'Waves', 'Down'),
  card('vocab', 55, 'In', 'Home', 'In'),
  card('vocab', 56, 'Out', 'Sun', 'Out'),
  card('vocab', 57, 'On', 'Lightbulb', 'On'),
  card('vocab', 58, 'Off', 'Moon', 'Off'),
  card('vocab', 59, 'Open', 'Book', 'Open'),
  card('vocab', 60, 'Close', 'Book', 'Close'),
  card('vocab', 61, 'Fast', 'Zap', 'Fast'),
  card('vocab', 62, 'Slow', 'Clock', 'Slow'),
  card('vocab', 63, 'Loud', 'Megaphone', 'Loud'),
  card('vocab', 64, 'Quiet', 'Bell', 'Quiet'),
  card('vocab', 65, 'Hot', 'Flame', 'Hot'),
  card('vocab', 66, 'Cold', 'Snowflake', 'Cold'),
  card('vocab', 67, 'Soft', 'Cloud', 'Soft'),
  card('vocab', 68, 'Hard', 'Blocks', 'Hard'),
  card('vocab', 69, 'Wet', 'Waves', 'Wet'),
  card('vocab', 70, 'Dry', 'Sun', 'Dry'),

  // Time
  card('vocab', 71, 'Now', 'Clock', 'Now'),
  card('vocab', 72, 'Later', 'Clock', 'Later'),
  card('vocab', 73, 'Today', 'Calendar', 'Today'),
  card('vocab', 74, 'Tomorrow', 'Calendar', 'Tomorrow'),
  card('vocab', 75, 'Yesterday', 'Calendar', 'Yesterday'),
  card('vocab', 76, 'Morning', 'Sunrise', 'Morning'),
  card('vocab', 77, 'Afternoon', 'Sun', 'Afternoon'),
  card('vocab', 78, 'Night', 'Moon', 'Night'),
  card('vocab', 79, 'Soon', 'Clock', 'Soon'),
  card('vocab', 80, 'Not Yet', 'Clock', 'Not yet'),

  // Social phrases
  card('vocab', 81, 'Hello', 'Smile', 'Hello'),
  card('vocab', 82, 'Goodbye', 'Hand', 'Goodbye'),
  card('vocab', 83, 'Good Morning', 'Sunrise', 'Good morning'),
  card('vocab', 84, 'Good Night', 'Moon', 'Good night'),
  card('vocab', 85, 'How Are You', 'Smile', 'How are you?'),
  card('vocab', 86, "I'm Okay", 'ThumbsUp', 'I am okay'),
  card('vocab', 87, 'Excuse Me', 'Hand', 'Excuse me'),
  card('vocab', 88, "I Don't Know", 'CircleHelp', 'I do not know'),
  card('vocab', 89, "I Don't Understand", 'CircleHelp', 'I do not understand'),
  card('vocab', 90, 'Say Again', 'Mic', 'Can you say that again?'),
  card('vocab', 91, 'Look', 'Eye', 'Look at this'),
  card('vocab', 92, 'Listen', 'Ear', 'Listen'),
  card('vocab', 93, 'Come Here', 'Hand', 'Come here'),
  card('vocab', 94, 'Go Away', 'Hand', 'Go away please'),
  card('vocab', 95, 'Play With Me', 'Users', 'Play with me'),
  card('vocab', 96, 'Leave Me Alone', 'User', 'Leave me alone please'),
  card('vocab', 97, "I'm Done", 'CircleCheck', 'I am done'),
  card('vocab', 98, 'Not Now', 'Clock', 'Not now'),
  card('vocab', 99, 'I Did It', 'Trophy', 'I did it!'),
  card('vocab', 100, 'Great Job', 'Star', 'Great job!'),
]

/**
 * Lookup premade cards by list model name (the plural API route name).
 * Returns undefined for unrecognized model names.
 */
export function getPremadeCards(
  listModelName: string,
): PremadeCard[] | PremadePlaceCard[] | undefined {
  switch (listModelName) {
    case 'foods':
      return PREMADE_FOODS
    case 'activities':
      return PREMADE_ACTIVITIES
    case 'places':
      return PREMADE_PLACES
    case 'villagers':
      return PREMADE_PEOPLE
    case 'vocabWords':
      return PREMADE_VOCAB_WORDS
    default:
      return undefined
  }
}
