import { card, PremadeCard } from './types'

/**
 * 125 pre-made activity cards with sensory and regulation focus.
 * Includes common activities, sensory tools, daily routines, and calming strategies
 * designed for individuals with autism.
 */
export const PREMADE_ACTIVITIES: PremadeCard[] = [
  card('activities', 1, 'Watch TV', 'Tv', 'I want to watch TV'),
  card(
    'activities',
    2,
    'Watch a Movie',
    'Clapperboard',
    'I want to watch a movie',
  ),
  card(
    'activities',
    3,
    'Play Video Games',
    'Gamepad',
    'I want to play video games',
  ),
  card(
    'activities',
    4,
    'Play on Tablet',
    'Computer',
    'I want to use the tablet',
  ),
  card(
    'activities',
    5,
    'Listen to Music',
    'Music',
    'I want to listen to music',
  ),
  card('activities', 6, 'Sing a Song', 'Mic', 'I want to sing'),
  card('activities', 7, 'Dance', 'Music', 'I want to dance'),
  card('activities', 8, 'Read a Book', 'Book', 'I want to read a book'),
  card('activities', 9, 'Draw', 'Pen', 'I want to draw'),
  card('activities', 10, 'Color', 'Palette', 'I want to color'),
  card('activities', 11, 'Paint', 'Paintbrush', 'I want to paint'),
  card(
    'activities',
    12,
    'Play with Clay',
    'Blocks',
    'I want to play with clay',
  ),
  card('activities', 13, 'Do a Puzzle', 'Puzzle', 'I want to do a puzzle'),
  card(
    'activities',
    14,
    'Build with Legos',
    'Blocks',
    'I want to build with Legos',
  ),
  card(
    'activities',
    15,
    'Build with Blocks',
    'Blocks',
    'I want to build with blocks',
  ),
  card(
    'activities',
    16,
    'Play with Trains',
    'Train',
    'I want to play with trains',
  ),
  card('activities', 17, 'Play with Cars', 'Car', 'I want to play with cars'),
  card(
    'activities',
    18,
    'Play with Dolls',
    'Heart',
    'I want to play with dolls',
  ),
  card(
    'activities',
    19,
    'Play with Action Figures',
    'Star',
    'I want to play with action figures',
  ),
  card('activities', 20, 'Play Pretend', 'Drama', 'I want to play pretend'),
  card('activities', 21, 'Play Outside', 'Sun', 'I want to play outside'),
  card(
    'activities',
    22,
    'Go to the Playground',
    'FerrisWheel',
    'I want to go to the playground',
  ),
  card('activities', 23, 'Swing', 'FerrisWheel', 'I want to swing'),
  card('activities', 24, 'Slide', 'FerrisWheel', 'I want to go on the slide'),
  card('activities', 25, 'Climb', 'Mountain', 'I want to climb'),
  card(
    'activities',
    26,
    'Jump on Trampoline',
    'Zap',
    'I want to jump on the trampoline',
  ),
  card('activities', 27, 'Ride a Bike', 'Bike', 'I want to ride my bike'),
  card('activities', 28, 'Ride a Scooter', 'Bike', 'I want to ride my scooter'),
  card(
    'activities',
    29,
    'Go for a Walk',
    'Footprints',
    'I want to go for a walk',
  ),
  card(
    'activities',
    30,
    'Go for a Run',
    'Footprints',
    'I want to go for a run',
  ),
  card('activities', 31, 'Play Catch', 'Volleyball', 'I want to play catch'),
  card('activities', 32, 'Kick a Ball', 'Volleyball', 'I want to kick a ball'),
  card(
    'activities',
    33,
    'Play Basketball',
    'Basketball',
    'I want to play basketball',
  ),
  card('activities', 34, 'Play Soccer', 'Volleyball', 'I want to play soccer'),
  card('activities', 35, 'Play Baseball', 'Trophy', 'I want to play baseball'),
  card('activities', 36, 'Go Swimming', 'Waves', 'I want to go swimming'),
  card(
    'activities',
    37,
    'Play in the Water',
    'Waves',
    'I want to play in the water',
  ),
  card('activities', 38, 'Take a Bath', 'Bath', 'I want to take a bath'),
  card('activities', 39, 'Blow Bubbles', 'Sparkles', 'I want to blow bubbles'),
  card('activities', 40, 'Play with Sand', 'Sun', 'I want to play with sand'),
  card('activities', 41, 'Fly a Kite', 'Wind', 'I want to fly a kite'),
  card('activities', 42, 'Go Camping', 'Tent', 'I want to go camping'),
  card(
    'activities',
    43,
    'Have a Picnic',
    'Utensils',
    'I want to have a picnic',
  ),
  card('activities', 44, 'Go Fishing', 'Fish', 'I want to go fishing'),
  card('activities', 45, 'Garden', 'Flower', 'I want to garden'),
  card(
    'activities',
    46,
    'Water the Plants',
    'Sprout',
    'I want to water the plants',
  ),
  card('activities', 47, 'Cook', 'Utensils', 'I want to help cook'),
  card('activities', 48, 'Bake', 'Cake', 'I want to bake'),
  card('activities', 49, 'Make a Snack', 'Cookie', 'I want to make a snack'),
  card(
    'activities',
    50,
    'Set the Table',
    'Utensils',
    'I want to set the table',
  ),
  card('activities', 51, 'Do Crafts', 'Scissors', 'I want to do crafts'),
  card('activities', 52, 'Make Jewelry', 'Gem', 'I want to make jewelry'),
  card(
    'activities',
    53,
    'Play with Stickers',
    'Star',
    'I want to play with stickers',
  ),
  card('activities', 54, 'Make a Card', 'Heart', 'I want to make a card'),
  card(
    'activities',
    55,
    'Play Board Games',
    'Dice',
    'I want to play a board game',
  ),
  card(
    'activities',
    56,
    'Play Card Games',
    'Dice',
    'I want to play card games',
  ),
  card(
    'activities',
    57,
    'Do a Science Experiment',
    'Atom',
    'I want to do a science experiment',
  ),
  card(
    'activities',
    58,
    'Look Through a Telescope',
    'Telescope',
    'I want to look at the stars',
  ),
  card(
    'activities',
    59,
    'Use a Magnifying Glass',
    'Search',
    'I want to explore',
  ),
  card(
    'activities',
    60,
    'Play with Magnets',
    'Magnet',
    'I want to play with magnets',
  ),
  card(
    'activities',
    61,
    'Play with Slime',
    'Sparkles',
    'I want to play with slime',
  ),
  card(
    'activities',
    62,
    'Play with Play-Doh',
    'Palette',
    'I want to play with Play-Doh',
  ),
  card(
    'activities',
    63,
    'Have a Playdate',
    'Users',
    'I want to have a playdate',
  ),
  card('activities', 64, 'Visit a Friend', 'Heart', 'I want to visit a friend'),
  card(
    'activities',
    65,
    'Talk on the Phone',
    'Phone',
    'I want to talk on the phone',
  ),
  card(
    'activities',
    66,
    'Video Call',
    'Camera',
    'I want to video call someone',
  ),
  card('activities', 67, 'Take Photos', 'Camera', 'I want to take photos'),
  card('activities', 68, 'Play Dress Up', 'Shirt', 'I want to play dress up'),
  card(
    'activities',
    69,
    'Play with Puppets',
    'Drama',
    'I want to play with puppets',
  ),
  card('activities', 70, 'Tell Stories', 'Book', 'I want to tell a story'),
  card(
    'activities',
    71,
    'Listen to a Story',
    'Headphones',
    'I want to hear a story',
  ),
  card('activities', 72, 'Do Homework', 'Pencil', 'I want to do homework'),
  card(
    'activities',
    73,
    'Practice Writing',
    'Pencil',
    'I want to practice writing',
  ),
  card('activities', 74, 'Practice Math', 'Calculator', 'I want to do math'),
  card('activities', 75, 'Learn Something New', 'Lightbulb', 'I want to learn'),
  card(
    'activities',
    76,
    'Play an Instrument',
    'Piano',
    'I want to play an instrument',
  ),
  card('activities', 77, 'Play Drums', 'Drum', 'I want to play drums'),
  card('activities', 78, 'Play Guitar', 'Guitar', 'I want to play guitar'),
  card('activities', 79, 'Exercise', 'Dumbbell', 'I want to exercise'),
  card('activities', 80, 'Do Yoga', 'Heart', 'I want to do yoga'),
  card('activities', 81, 'Stretch', 'Dumbbell', 'I want to stretch'),
  card('activities', 82, 'Play Tag', 'Zap', 'I want to play tag'),
  card(
    'activities',
    83,
    'Play Hide and Seek',
    'Eye',
    'I want to play hide and seek',
  ),
  card('activities', 84, 'Race', 'Zap', 'I want to race'),
  card('activities', 85, 'Hula Hoop', 'CirclePlay', 'I want to hula hoop'),
  card('activities', 86, 'Jump Rope', 'Zap', 'I want to jump rope'),
  card(
    'activities',
    87,
    'Ride in the Car',
    'Car',
    'I want to go for a car ride',
  ),
  card(
    'activities',
    88,
    'Go on an Adventure',
    'Compass',
    'I want to go on an adventure',
  ),
  card('activities', 89, 'Explore Nature', 'Leaf', 'I want to explore nature'),
  card(
    'activities',
    90,
    'Watch Animals',
    'PawPrint',
    'I want to watch animals',
  ),
  card(
    'activities',
    91,
    'Pet an Animal',
    'PawPrint',
    'I want to pet an animal',
  ),
  card('activities', 92, 'Feed the Fish', 'Fish', 'I want to feed the fish'),
  card(
    'activities',
    93,
    'Play with the Dog',
    'Dog',
    'I want to play with the dog',
  ),
  card(
    'activities',
    94,
    'Play with the Cat',
    'Cat',
    'I want to play with the cat',
  ),
  card('activities', 95, 'Build a Fort', 'Castle', 'I want to build a fort'),
  card(
    'activities',
    96,
    'Have a Tea Party',
    'Coffee',
    'I want to have a tea party',
  ),
  card(
    'activities',
    97,
    'Play in the Snow',
    'Snowflake',
    'I want to play in the snow',
  ),
  card(
    'activities',
    98,
    'Build a Snowman',
    'Snowflake',
    'I want to build a snowman',
  ),
  card(
    'activities',
    99,
    'Play in the Rain',
    'CloudRain',
    'I want to play in the rain',
  ),
  card('activities', 100, 'Relax', 'Sofa', 'I want to relax'),
  // Additional activities - sensory, regulation, and daily routines (101-125)
  card('activities', 101, 'Fidget Toy', 'CircleDot', 'I want my fidget toy'),
  card('activities', 102, 'Sensory Bin', 'Blocks', 'I want the sensory bin'),
  card(
    'activities',
    103,
    'Therapy Ball',
    'CirclePlay',
    'I want to bounce on the ball',
  ),
  card(
    'activities',
    104,
    'Rocking Chair',
    'Sofa',
    'I want to rock in the chair',
  ),
  card(
    'activities',
    105,
    'Squeeze Pillows',
    'Blocks',
    'I want to squeeze pillows',
  ),
  card(
    'activities',
    106,
    'Weighted Blanket',
    'Blocks',
    'I want my weighted blanket',
  ),
  card('activities', 107, 'Watch YouTube', 'Tv', 'I want to watch YouTube'),
  card(
    'activities',
    108,
    'Watch Videos',
    'Clapperboard',
    'I want to watch videos',
  ),
  card('activities', 109, 'Use My Phone', 'Phone', 'I want to use my phone'),
  card('activities', 110, 'Quiet Time', 'Moon', 'I need quiet time'),
  card('activities', 111, 'Sit Quietly', 'Sofa', 'I want to sit quietly'),
  card('activities', 112, 'Get Tickled', 'Laugh', 'I want to be tickled'),
  card('activities', 113, 'Chase Me', 'Zap', 'Chase me'),
  card('activities', 114, 'Spin Around', 'CirclePlay', 'I want to spin'),
  card('activities', 115, 'Wrestle', 'Dumbbell', 'I want to wrestle'),
  card('activities', 116, 'Brush Teeth', 'Smile', 'I want to brush my teeth'),
  card('activities', 117, 'Wash Hands', 'Hand', 'I want to wash my hands'),
  card('activities', 118, 'Get Dressed', 'Shirt', 'I want to get dressed'),
  card('activities', 119, 'Pack Backpack', 'Backpack', 'I want to pack my bag'),
  card('activities', 120, 'Clean Up', 'Trash', 'I want to clean up'),
  card(
    'activities',
    121,
    'Make Choices',
    'CircleHelp',
    'I want to make choices',
  ),
  card(
    'activities',
    122,
    'Look at Pictures',
    'Image',
    'I want to see pictures',
  ),
  card('activities', 123, 'Deep Pressure', 'Hand', 'I need a squeeze'),
  card(
    'activities',
    124,
    'Use My Device',
    'Computer',
    'I want to use my device',
  ),
  card('activities', 125, 'Calm Down Corner', 'Heart', 'I need my calm space'),
]
