import { card, PremadeCard } from './types'

/**
 * Pre-made food cards for autistic children learning to communicate.
 * Includes 125 cards covering meals, snacks, drinks, condiments, and
 * various textures/preferences commonly seen in autism support.
 */
export const PREMADE_FOODS: PremadeCard[] = [
  card('foods', 1, 'Pizza', 'Pizza', 'I want pizza'),
  card('foods', 2, 'Chicken Nuggets', 'Drumstick', 'I want chicken nuggets'),
  card('foods', 3, 'Mac and Cheese', 'Wheat', 'I want mac and cheese'),
  card('foods', 4, 'Grilled Cheese', 'Sandwich', 'I want grilled cheese'),
  card('foods', 5, 'Hot Dog', 'Beef', 'I want a hot dog'),
  card('foods', 6, 'Hamburger', 'Beef', 'I want a hamburger'),
  card('foods', 7, 'French Fries', 'Utensils', 'I want french fries'),
  card('foods', 8, 'Spaghetti', 'Utensils', 'I want spaghetti'),
  card('foods', 9, 'Tacos', 'Utensils', 'I want tacos'),
  card('foods', 10, 'Rice', 'Wheat', 'I want rice'),
  card('foods', 11, 'Soup', 'Soup', 'I want soup'),
  card('foods', 12, 'Sandwich', 'Sandwich', 'I want a sandwich'),
  card('foods', 13, 'Toast', 'Croissant', 'I want toast'),
  card('foods', 14, 'Pancakes', 'Cake', 'I want pancakes'),
  card('foods', 15, 'Waffles', 'Cake', 'I want waffles'),
  card('foods', 16, 'Cereal', 'Milk', 'I want cereal'),
  card('foods', 17, 'Oatmeal', 'Wheat', 'I want oatmeal'),
  card('foods', 18, 'Eggs', 'Egg', 'I want eggs'),
  card('foods', 19, 'Bacon', 'Beef', 'I want bacon'),
  card('foods', 20, 'Yogurt', 'CupSoda', 'I want yogurt'),
  card('foods', 21, 'Apple', 'Apple', 'I want an apple'),
  card('foods', 22, 'Banana', 'Banana', 'I want a banana'),
  card('foods', 23, 'Grapes', 'Grape', 'I want grapes'),
  card('foods', 24, 'Strawberries', 'Cherry', 'I want strawberries'),
  card('foods', 25, 'Blueberries', 'Cherry', 'I want blueberries'),
  card('foods', 26, 'Orange', 'Citrus', 'I want an orange'),
  card('foods', 27, 'Watermelon', 'Apple', 'I want watermelon'),
  card('foods', 28, 'Pineapple', 'Citrus', 'I want pineapple'),
  card('foods', 29, 'Mango', 'Citrus', 'I want mango'),
  card('foods', 30, 'Peach', 'Apple', 'I want a peach'),
  card('foods', 31, 'Carrots', 'Carrot', 'I want carrots'),
  card('foods', 32, 'Broccoli', 'Leaf', 'I want broccoli'),
  card('foods', 33, 'Corn', 'Wheat', 'I want corn'),
  card('foods', 34, 'Green Beans', 'Bean', 'I want green beans'),
  card('foods', 35, 'Peas', 'Bean', 'I want peas'),
  card('foods', 36, 'Mashed Potatoes', 'Utensils', 'I want mashed potatoes'),
  card('foods', 37, 'Sweet Potato', 'Carrot', 'I want sweet potato'),
  card('foods', 38, 'Salad', 'Salad', 'I want a salad'),
  card('foods', 39, 'Celery', 'Leaf', 'I want celery'),
  card('foods', 40, 'Cucumber', 'Salad', 'I want cucumber'),
  card('foods', 41, 'Cheese', 'Sandwich', 'I want cheese'),
  card('foods', 42, 'Crackers', 'Cookie', 'I want crackers'),
  card('foods', 43, 'Goldfish Crackers', 'Fish', 'I want goldfish crackers'),
  card('foods', 44, 'Pretzels', 'Cookie', 'I want pretzels'),
  card('foods', 45, 'Chips', 'Utensils', 'I want chips'),
  card('foods', 46, 'Popcorn', 'Popcorn', 'I want popcorn'),
  card('foods', 47, 'Trail Mix', 'Nut', 'I want trail mix'),
  card('foods', 48, 'Granola Bar', 'Wheat', 'I want a granola bar'),
  card('foods', 49, 'Fruit Snacks', 'Cherry', 'I want fruit snacks'),
  card('foods', 50, 'Applesauce', 'Apple', 'I want applesauce'),
  card('foods', 51, 'Peanut Butter', 'Nut', 'I want peanut butter'),
  card('foods', 52, 'Jelly Sandwich', 'Sandwich', 'I want a jelly sandwich'),
  card('foods', 53, 'Bagel', 'Croissant', 'I want a bagel'),
  card('foods', 54, 'Muffin', 'Cake', 'I want a muffin'),
  card('foods', 55, 'Donut', 'Cookie', 'I want a donut'),
  card('foods', 56, 'Cookie', 'Cookie', 'I want a cookie'),
  card('foods', 57, 'Brownie', 'Cake', 'I want a brownie'),
  card('foods', 58, 'Cake', 'Cake', 'I want cake'),
  card('foods', 59, 'Ice Cream', 'IceCream', 'I want ice cream'),
  card('foods', 60, 'Popsicle', 'IceCream', 'I want a popsicle'),
  card('foods', 61, 'Pudding', 'CupSoda', 'I want pudding'),
  card('foods', 62, 'Jello', 'CupSoda', 'I want jello'),
  card('foods', 63, 'Candy', 'Candy', 'I want candy'),
  card('foods', 64, 'Chocolate', 'Candy', 'I want chocolate'),
  card('foods', 65, 'Lollipop', 'Lollipop', 'I want a lollipop'),
  card('foods', 66, 'Gummy Bears', 'Candy', 'I want gummy bears'),
  card('foods', 67, 'Water', 'GlassWater', 'I want water'),
  card('foods', 68, 'Milk', 'Milk', 'I want milk'),
  card('foods', 69, 'Chocolate Milk', 'Milk', 'I want chocolate milk'),
  card('foods', 70, 'Juice', 'CupSoda', 'I want juice'),
  card('foods', 71, 'Apple Juice', 'Apple', 'I want apple juice'),
  card('foods', 72, 'Orange Juice', 'Citrus', 'I want orange juice'),
  card('foods', 73, 'Lemonade', 'Citrus', 'I want lemonade'),
  card('foods', 74, 'Smoothie', 'CupSoda', 'I want a smoothie'),
  card('foods', 75, 'Hot Chocolate', 'Coffee', 'I want hot chocolate'),
  card('foods', 76, 'Chicken Soup', 'Soup', 'I want chicken soup'),
  card('foods', 77, 'Tomato Soup', 'Soup', 'I want tomato soup'),
  card('foods', 78, 'Fish Sticks', 'Fish', 'I want fish sticks'),
  card('foods', 79, 'Shrimp', 'Fish', 'I want shrimp'),
  card('foods', 80, 'Steak', 'Beef', 'I want steak'),
  card('foods', 81, 'Chicken Breast', 'Drumstick', 'I want chicken'),
  card('foods', 82, 'Turkey', 'Drumstick', 'I want turkey'),
  card('foods', 83, 'Ham', 'Beef', 'I want ham'),
  card('foods', 84, 'Meatballs', 'Beef', 'I want meatballs'),
  card('foods', 85, 'Burrito', 'Utensils', 'I want a burrito'),
  card('foods', 86, 'Quesadilla', 'Utensils', 'I want a quesadilla'),
  card('foods', 87, 'Nachos', 'Utensils', 'I want nachos'),
  card('foods', 88, 'Fried Rice', 'Wheat', 'I want fried rice'),
  card('foods', 89, 'Noodles', 'Utensils', 'I want noodles'),
  card('foods', 90, 'Ramen', 'Soup', 'I want ramen'),
  card('foods', 91, 'Bread', 'Croissant', 'I want bread'),
  card('foods', 92, 'Butter', 'Sandwich', 'I want butter'),
  card('foods', 93, 'Jam', 'Cherry', 'I want jam'),
  card('foods', 94, 'Honey', 'Flower', 'I want honey'),
  card('foods', 95, 'Ketchup', 'CupSoda', 'I want ketchup'),
  card('foods', 96, 'Ranch', 'CupSoda', 'I want ranch'),
  card('foods', 97, 'Syrup', 'CupSoda', 'I want syrup'),
  card('foods', 98, 'Raisins', 'Grape', 'I want raisins'),
  card('foods', 99, 'Dried Fruit', 'Cherry', 'I want dried fruit'),
  card('foods', 100, 'String Cheese', 'Sandwich', 'I want string cheese'),
  // Additional foods - common preferences and textures (101-125)
  card('foods', 101, 'Chicken Tenders', 'Drumstick', 'I want chicken tenders'),
  card('foods', 102, 'Corn Dog', 'Beef', 'I want a corn dog'),
  card('foods', 103, 'Tater Tots', 'Utensils', 'I want tater tots'),
  card('foods', 104, 'French Toast', 'Croissant', 'I want french toast'),
  card('foods', 105, 'Sausage', 'Beef', 'I want sausage'),
  card('foods', 106, 'Hash Browns', 'Utensils', 'I want hash browns'),
  card('foods', 107, 'Veggie Straws', 'Carrot', 'I want veggie straws'),
  card('foods', 108, 'Animal Crackers', 'Cookie', 'I want animal crackers'),
  card('foods', 109, 'Graham Crackers', 'Cookie', 'I want graham crackers'),
  card('foods', 110, 'Cheese Balls', 'Sandwich', 'I want cheese balls'),
  card('foods', 111, 'Rice Cakes', 'Wheat', 'I want rice cakes'),
  card('foods', 112, 'Fruit Pouch', 'Cherry', 'I want a fruit pouch'),
  card('foods', 113, 'Go-Gurt', 'CupSoda', 'I want go-gurt'),
  card('foods', 114, 'Soda', 'CupSoda', 'I want soda'),
  card('foods', 115, 'Tea', 'Coffee', 'I want tea'),
  card('foods', 116, 'Sports Drink', 'CupSoda', 'I want a sports drink'),
  card('foods', 117, 'Fruit Punch', 'CupSoda', 'I want fruit punch'),
  card('foods', 118, 'Grape Juice', 'Grape', 'I want grape juice'),
  card('foods', 119, 'Mustard', 'CupSoda', 'I want mustard'),
  card('foods', 120, 'BBQ Sauce', 'CupSoda', 'I want BBQ sauce'),
  card('foods', 121, 'Salsa', 'Utensils', 'I want salsa'),
  card('foods', 122, 'Guacamole', 'Apple', 'I want guacamole'),
  card('foods', 123, 'Pickles', 'Salad', 'I want pickles'),
  card('foods', 124, 'Olives', 'Salad', 'I want olives'),
  card('foods', 125, 'Hummus', 'CupSoda', 'I want hummus'),
]
