import { card, PremadeCard } from './types'

/**
 * 110 pre-made people cards including behavioral supports and key roles.
 * Covers family members, school staff, therapists, community helpers, and autism-specific
 * support professionals like BCBAs, RBTs, and paraprofessionals.
 */
export const PREMADE_PEOPLE: PremadeCard[] = [
  card('people', 1, 'Mom', 'Heart', 'I want to see Mom'),
  card('people', 2, 'Dad', 'Heart', 'I want to see Dad'),
  card('people', 3, 'Brother', 'User', 'I want to see my brother'),
  card('people', 4, 'Sister', 'User', 'I want to see my sister'),
  card('people', 5, 'Grandma', 'Heart', 'I want to see Grandma'),
  card('people', 6, 'Grandpa', 'Heart', 'I want to see Grandpa'),
  card('people', 7, 'Aunt', 'User', 'I want to see my aunt'),
  card('people', 8, 'Uncle', 'User', 'I want to see my uncle'),
  card('people', 9, 'Cousin', 'User', 'I want to see my cousin'),
  card('people', 10, 'Baby', 'Baby', 'I want to see the baby'),
  card(
    'people',
    11,
    'Best Friend',
    'HeartHandshake',
    'I want to see my best friend',
  ),
  card('people', 12, 'Friend', 'Users', 'I want to see my friend'),
  card('people', 13, 'Neighbor', 'Home', 'I want to see the neighbor'),
  card('people', 14, 'Teacher', 'GraduationCap', 'I want to see my teacher'),
  card('people', 15, 'Principal', 'School', 'I want to see the principal'),
  card(
    'people',
    16,
    'School Counselor',
    'Heart',
    'I want to see the counselor',
  ),
  card('people', 17, 'Bus Driver', 'Bus', 'I want to see the bus driver'),
  card('people', 18, 'Therapist', 'Heart', 'I want to see my therapist'),
  card(
    'people',
    19,
    'Speech Therapist',
    'Mic',
    'I want to see my speech therapist',
  ),
  card('people', 20, 'Doctor', 'Stethoscope', 'I want to see the doctor'),
  card('people', 21, 'Dentist', 'Smile', 'I want to see the dentist'),
  card('people', 22, 'Nurse', 'Stethoscope', 'I want to see the nurse'),
  card('people', 23, 'Coach', 'Trophy', 'I want to see my coach'),
  card(
    'people',
    24,
    'Music Teacher',
    'Music',
    'I want to see my music teacher',
  ),
  card('people', 25, 'Art Teacher', 'Palette', 'I want to see my art teacher'),
  card('people', 26, 'Librarian', 'Library', 'I want to see the librarian'),
  card('people', 27, 'Babysitter', 'Heart', 'I want to see the babysitter'),
  card('people', 28, 'Nanny', 'Heart', 'I want to see my nanny'),
  card('people', 29, 'Tutor', 'Book', 'I want to see my tutor'),
  card('people', 30, 'Pastor', 'Church', 'I want to see the pastor'),
  card(
    'people',
    31,
    'Sunday School Teacher',
    'Book',
    'I want to see my Sunday school teacher',
  ),
  card('people', 32, 'Aide', 'HandHelping', 'I want to see my aide'),
  card(
    'people',
    33,
    'Classroom Helper',
    'HandHelping',
    'I want to see the helper',
  ),
  card('people', 34, 'Pet', 'PawPrint', 'I want to see my pet'),
  card('people', 35, 'Dog', 'Dog', 'I want to see the dog'),
  card('people', 36, 'Cat', 'Cat', 'I want to see the cat'),
  card('people', 37, 'Classmate', 'Users', 'I want to see my classmate'),
  card('people', 38, 'Teammate', 'Users', 'I want to see my teammate'),
  card('people', 39, 'Pen Pal', 'Pen', 'I want to write to my pen pal'),
  card('people', 40, 'Godparent', 'Heart', 'I want to see my godparent'),
  card('people', 41, 'Step-Mom', 'Heart', 'I want to see my step-mom'),
  card('people', 42, 'Step-Dad', 'Heart', 'I want to see my step-dad'),
  card('people', 43, 'Step-Brother', 'User', 'I want to see my step-brother'),
  card('people', 44, 'Step-Sister', 'User', 'I want to see my step-sister'),
  card('people', 45, 'Half-Brother', 'User', 'I want to see my half-brother'),
  card('people', 46, 'Half-Sister', 'User', 'I want to see my half-sister'),
  card('people', 47, 'Great Grandma', 'Heart', 'I want to see great grandma'),
  card('people', 48, 'Great Grandpa', 'Heart', 'I want to see great grandpa'),
  card(
    'people',
    49,
    'Foster Parent',
    'Heart',
    'I want to see my foster parent',
  ),
  card(
    'people',
    50,
    'Social Worker',
    'Clipboard',
    'I want to see my social worker',
  ),
  card('people', 51, 'Occupational Therapist', 'Hand', 'I want to see my OT'),
  card('people', 52, 'Physical Therapist', 'Dumbbell', 'I want to see my PT'),
  card('people', 53, 'Psychologist', 'Brain', 'I want to see my psychologist'),
  card('people', 54, 'Eye Doctor', 'Eye', 'I want to see the eye doctor'),
  card('people', 55, 'Ear Doctor', 'Ear', 'I want to see the ear doctor'),
  card('people', 56, 'Pharmacist', 'Pill', 'I want to see the pharmacist'),
  card('people', 57, 'Firefighter', 'Flame', 'I want to see a firefighter'),
  card(
    'people',
    58,
    'Police Officer',
    'Siren',
    'I want to see a police officer',
  ),
  card('people', 59, 'Mail Carrier', 'Flag', 'I want to see the mail carrier'),
  card(
    'people',
    60,
    'Crossing Guard',
    'Hand',
    'I want to see the crossing guard',
  ),
  card('people', 61, 'Lunch Lady', 'Utensils', 'I want to see the lunch lady'),
  card('people', 62, 'Janitor', 'Wrench', 'I want to see the janitor'),
  card(
    'people',
    63,
    'School Secretary',
    'Clipboard',
    'I want to see the school secretary',
  ),
  card(
    'people',
    64,
    'Camp Counselor',
    'Tent',
    'I want to see my camp counselor',
  ),
  card(
    'people',
    65,
    'Swim Instructor',
    'Waves',
    'I want to see my swim teacher',
  ),
  card(
    'people',
    66,
    'Dance Teacher',
    'Music',
    'I want to see my dance teacher',
  ),
  card(
    'people',
    67,
    'Karate Teacher',
    'Medal',
    'I want to see my karate teacher',
  ),
  card(
    'people',
    68,
    'Guitar Teacher',
    'Guitar',
    'I want to see my guitar teacher',
  ),
  card(
    'people',
    69,
    'Piano Teacher',
    'Piano',
    'I want to see my piano teacher',
  ),
  card('people', 70, 'Drum Teacher', 'Drum', 'I want to see my drum teacher'),
  card(
    'people',
    71,
    'Riding Instructor',
    'PawPrint',
    'I want to see my riding teacher',
  ),
  card('people', 72, 'Scout Leader', 'Flag', 'I want to see my scout leader'),
  card('people', 73, 'Volunteer', 'HandHelping', 'I want to see the volunteer'),
  card(
    'people',
    74,
    'Big Brother/Sister',
    'HeartHandshake',
    'I want to see my big buddy',
  ),
  card('people', 75, 'Mentor', 'Star', 'I want to see my mentor'),
  card('people', 76, 'New Friend', 'Sparkles', 'I met a new friend'),
  card('people', 77, 'Old Friend', 'Heart', 'I miss my old friend'),
  card('people', 78, 'Playdate Friend', 'Users', 'I want to have a playdate'),
  card(
    'people',
    79,
    'Church Friend',
    'Church',
    'I want to see my church friend',
  ),
  card(
    'people',
    80,
    'Sport Friend',
    'Trophy',
    'I want to see my sports friend',
  ),
  card(
    'people',
    81,
    'School Friend',
    'School',
    'I want to see my school friend',
  ),
  card(
    'people',
    82,
    'Neighbor Kid',
    'Home',
    'I want to play with the neighbor kid',
  ),
  card(
    'people',
    83,
    'Family Friend',
    'Users',
    'I want to see our family friends',
  ),
  card('people', 84, 'Older Sibling', 'User', 'I want to see my older sibling'),
  card(
    'people',
    85,
    'Younger Sibling',
    'Baby',
    'I want to see my younger sibling',
  ),
  card('people', 86, 'Twin', 'Users', 'I want to see my twin'),
  card('people', 87, 'Niece', 'User', 'I want to see my niece'),
  card('people', 88, 'Nephew', 'User', 'I want to see my nephew'),
  card('people', 89, 'Family', 'Users', 'I want to see my family'),
  card('people', 90, 'Everyone', 'Users', 'I want to see everyone'),
  card('people', 91, 'No One', 'User', 'I want to be alone'),
  card('people', 92, 'Someone New', 'Sparkles', 'I want to meet someone new'),
  card('people', 93, 'Helper', 'HandHelping', 'I need a helper'),
  card('people', 94, 'Grown-Up', 'User', 'I need a grown-up'),
  card('people', 95, 'Kid', 'User', 'I want to play with a kid'),
  card('people', 96, 'Girl', 'User', 'I want to see a girl'),
  card('people', 97, 'Boy', 'User', 'I want to see a boy'),
  card('people', 98, 'Group', 'Users', 'I want to be in a group'),
  card('people', 99, 'Nobody', 'User', 'I do not want to see anyone'),
  card('people', 100, 'Myself', 'Smile', 'I want time for me'),
  // Additional people - behavioral supports and key roles (101-110)
  card('people', 101, 'BCBA', 'Brain', 'I want to see my BCBA'),
  card(
    'people',
    102,
    'Behavior Therapist',
    'Heart',
    'I want to see my behavior therapist',
  ),
  card(
    'people',
    103,
    'ABA Therapist',
    'Brain',
    'I want to see my ABA therapist',
  ),
  card('people', 104, 'RBT', 'HandHelping', 'I want to see my RBT'),
  card('people', 105, '1:1 Aide', 'HandHelping', 'I want to see my 1:1 aide'),
  card('people', 106, 'Paraprofessional', 'School', 'I want to see my para'),
  card('people', 107, 'Shadow', 'HandHelping', 'I want to see my shadow'),
  card(
    'people',
    108,
    'Online Friend',
    'Computer',
    'I want to see my online friend',
  ),
  card(
    'people',
    109,
    'Video Game Friend',
    'Gamepad',
    'I want to play with my gaming friend',
  ),
  card(
    'people',
    110,
    'Support Person',
    'HeartHandshake',
    'I want to see my support person',
  ),
]
