import { placeCard, PremadePlaceCard } from './types'

/**
 * 120 pre-made place cards including home rooms and sensory-friendly locations.
 * Covers common destinations, specific stores, therapy locations, and rooms within
 * the home for individuals with autism.
 */
export const PREMADE_PLACES: PremadePlaceCard[] = [
  placeCard(1, 'Home', 'Home', 'I want to go home'),
  placeCard(2, 'School', 'School', 'I want to go to school'),
  placeCard(3, "Grandma's House", 'Home', "I want to go to grandma's"),
  placeCard(4, "Grandpa's House", 'Home', "I want to go to grandpa's"),
  placeCard(5, "Mom's House", 'Home', "I want to go to mom's house"),
  placeCard(6, "Dad's House", 'Home', "I want to go to dad's house"),
  placeCard(7, "Friend's House", 'Home', "I want to go to my friend's house"),
  placeCard(8, 'Park', 'Tree', 'I want to go to the park'),
  placeCard(9, 'Playground', 'FerrisWheel', 'I want to go to the playground'),
  placeCard(10, 'Library', 'Library', 'I want to go to the library'),
  placeCard(
    11,
    'Grocery Store',
    'ShoppingCart',
    'I want to go to the grocery store',
  ),
  placeCard(12, 'Mall', 'Store', 'I want to go to the mall'),
  placeCard(13, 'Toy Store', 'Blocks', 'I want to go to the toy store'),
  placeCard(14, 'Bookstore', 'Book', 'I want to go to the bookstore'),
  placeCard(15, 'Pet Store', 'PawPrint', 'I want to go to the pet store'),
  placeCard(16, 'Restaurant', 'Utensils', 'I want to go to a restaurant'),
  placeCard(17, 'Fast Food', 'Pizza', 'I want to go get fast food'),
  placeCard(18, 'Ice Cream Shop', 'IceCream', 'I want to go get ice cream'),
  placeCard(19, 'Bakery', 'Croissant', 'I want to go to the bakery'),
  placeCard(20, 'Coffee Shop', 'Coffee', 'I want to go to the coffee shop'),
  placeCard(21, 'Pizza Place', 'Pizza', 'I want to go get pizza'),
  placeCard(22, "Doctor's Office", 'Stethoscope', 'I need to go to the doctor'),
  placeCard(23, 'Dentist', 'Smile', 'I need to go to the dentist'),
  placeCard(24, 'Hospital', 'Hospital', 'I need to go to the hospital'),
  placeCard(25, 'Pharmacy', 'Pill', 'I need to go to the pharmacy'),
  placeCard(26, 'Church', 'Church', 'I want to go to church'),
  placeCard(27, 'Movie Theater', 'Clapperboard', 'I want to go to the movies'),
  placeCard(28, 'Arcade', 'Gamepad', 'I want to go to the arcade'),
  placeCard(29, 'Bowling Alley', 'Trophy', 'I want to go bowling'),
  placeCard(30, 'Swimming Pool', 'Waves', 'I want to go to the pool'),
  placeCard(31, 'Beach', 'Sun', 'I want to go to the beach'),
  placeCard(32, 'Lake', 'Waves', 'I want to go to the lake'),
  placeCard(33, 'River', 'Waves', 'I want to go to the river'),
  placeCard(34, 'Zoo', 'PawPrint', 'I want to go to the zoo'),
  placeCard(35, 'Aquarium', 'Fish', 'I want to go to the aquarium'),
  placeCard(36, 'Museum', 'Landmark', 'I want to go to the museum'),
  placeCard(
    37,
    'Amusement Park',
    'RollerCoaster',
    'I want to go to the amusement park',
  ),
  placeCard(38, 'Water Park', 'Waves', 'I want to go to the water park'),
  placeCard(
    39,
    'Trampoline Park',
    'Zap',
    'I want to go to the trampoline park',
  ),
  placeCard(40, 'Skating Rink', 'Snowflake', 'I want to go skating'),
  placeCard(41, 'Gym', 'Dumbbell', 'I want to go to the gym'),
  placeCard(42, 'Dance Studio', 'Music', 'I want to go to dance class'),
  placeCard(43, 'Music Class', 'Piano', 'I want to go to music class'),
  placeCard(44, 'Art Class', 'Palette', 'I want to go to art class'),
  placeCard(45, 'Karate', 'Medal', 'I want to go to karate'),
  placeCard(
    46,
    'Soccer Field',
    'Volleyball',
    'I want to go to the soccer field',
  ),
  placeCard(
    47,
    'Baseball Field',
    'Trophy',
    'I want to go to the baseball field',
  ),
  placeCard(
    48,
    'Basketball Court',
    'Basketball',
    'I want to go play basketball',
  ),
  placeCard(49, 'Tennis Court', 'Trophy', 'I want to play tennis'),
  placeCard(
    50,
    'Football Field',
    'Trophy',
    'I want to go to the football field',
  ),
  placeCard(51, 'Skate Park', 'Bike', 'I want to go to the skate park'),
  placeCard(52, 'Dog Park', 'Dog', 'I want to go to the dog park'),
  placeCard(53, 'Farm', 'Tractor', 'I want to go to the farm'),
  placeCard(54, 'Garden', 'Flower', 'I want to go to the garden'),
  placeCard(55, 'Forest', 'Tree', 'I want to go to the forest'),
  placeCard(56, 'Mountain', 'Mountain', 'I want to go to the mountain'),
  placeCard(57, 'Camping', 'Tent', 'I want to go camping'),
  placeCard(58, 'Hiking Trail', 'Mountain', 'I want to go hiking'),
  placeCard(59, 'Bike Path', 'Bike', 'I want to go on the bike path'),
  placeCard(60, 'Nature Center', 'Leaf', 'I want to go to the nature center'),
  placeCard(61, 'Clothing Store', 'Shirt', 'I want to go clothes shopping'),
  placeCard(62, 'Shoe Store', 'ShoppingBag', 'I want to go buy shoes'),
  placeCard(63, 'Dollar Store', 'Coins', 'I want to go to the dollar store'),
  placeCard(
    64,
    'Hardware Store',
    'Hammer',
    'I want to go to the hardware store',
  ),
  placeCard(65, 'Gas Station', 'Car', 'We need to get gas'),
  placeCard(66, 'Car Wash', 'Car', 'I want to go to the car wash'),
  placeCard(67, 'Bank', 'PiggyBank', 'I want to go to the bank'),
  placeCard(68, 'Post Office', 'Flag', 'I want to go to the post office'),
  placeCard(69, 'Fire Station', 'Flame', 'I want to see the fire station'),
  placeCard(70, 'Police Station', 'Siren', 'I want to see the police station'),
  placeCard(71, 'Airport', 'Plane', 'I want to go to the airport'),
  placeCard(72, 'Train Station', 'Train', 'I want to go to the train station'),
  placeCard(73, 'Bus Stop', 'Bus', 'I want to go to the bus stop'),
  placeCard(74, 'Barber Shop', 'Scissors', 'I need a haircut'),
  placeCard(75, 'Laundromat', 'Shirt', 'I want to go do laundry'),
  placeCard(76, 'Therapy', 'Heart', 'I want to go to therapy'),
  placeCard(77, 'Speech Therapy', 'Mic', 'I want to go to speech therapy'),
  placeCard(78, 'Occupational Therapy', 'Hand', 'I want to go to OT'),
  placeCard(79, "Relative's House", 'Home', 'I want to visit family'),
  placeCard(80, "Neighbor's House", 'Home', "I want to go to the neighbor's"),
  placeCard(81, 'Birthday Party', 'PartyPopper', 'I want to go to a party'),
  placeCard(82, 'Sleepover', 'Moon', 'I want to go to a sleepover'),
  placeCard(
    83,
    'Playground by School',
    'FerrisWheel',
    'I want to play at the school playground',
  ),
  placeCard(84, 'Sports Practice', 'Dumbbell', 'I want to go to practice'),
  placeCard(85, 'Tutoring', 'GraduationCap', 'I want to go to tutoring'),
  placeCard(86, 'Sunday School', 'Book', 'I want to go to Sunday school'),
  placeCard(87, 'Daycare', 'Baby', 'I need to go to daycare'),
  placeCard(
    88,
    'After School Program',
    'Clock',
    'I want to go to after school',
  ),
  placeCard(89, 'Summer Camp', 'Tent', 'I want to go to camp'),
  placeCard(90, 'Vacation', 'Plane', 'I want to go on vacation'),
  placeCard(91, 'Hotel', 'Hotel', 'We are staying at a hotel'),
  placeCard(92, 'Cabin', 'Home', 'I want to go to the cabin'),
  placeCard(93, 'Waterfall', 'Waves', 'I want to see a waterfall'),
  placeCard(94, 'Botanical Garden', 'Flower', 'I want to see the gardens'),
  placeCard(95, 'Science Center', 'Atom', 'I want to go to the science center'),
  placeCard(96, 'Planetarium', 'Star', 'I want to go to the planetarium'),
  placeCard(97, 'Concert', 'Music', 'I want to go to a concert'),
  placeCard(98, 'Fair', 'FerrisWheel', 'I want to go to the fair'),
  placeCard(99, 'Parade', 'Flag', 'I want to see the parade'),
  placeCard(
    100,
    'Farmers Market',
    'Apple',
    'I want to go to the farmers market',
  ),
  // Additional places - home rooms, stores, and sensory-friendly locations (101-120)
  placeCard(101, 'My Room', 'Bed', 'I want to go to my room'),
  placeCard(102, 'Kitchen', 'Utensils', 'I want to go to the kitchen'),
  placeCard(103, 'Living Room', 'Tv', 'I want to go to the living room'),
  placeCard(104, 'Bathroom', 'Bath', 'I want to go to the bathroom'),
  placeCard(105, 'Backyard', 'Tree', 'I want to go to the backyard'),
  placeCard(106, 'Basement', 'Home', 'I want to go to the basement'),
  placeCard(107, 'Playroom', 'Blocks', 'I want to go to the playroom'),
  placeCard(108, 'Quiet Corner', 'Sofa', 'I want to go to my quiet corner'),
  placeCard(
    109,
    'Sensory Room',
    'Sparkles',
    'I want to go to the sensory room',
  ),
  placeCard(
    110,
    'My Special Place',
    'Heart',
    'I want to go to my special place',
  ),
  placeCard(111, 'Target', 'Store', 'I want to go to Target'),
  placeCard(112, 'Walmart', 'ShoppingCart', 'I want to go to Walmart'),
  placeCard(113, "McDonald's", 'Pizza', "I want to go to McDonald's"),
  placeCard(114, 'Chick-fil-A', 'Drumstick', 'I want to go to Chick-fil-A'),
  placeCard(115, 'Sensory Gym', 'Dumbbell', 'I want to go to the sensory gym'),
  placeCard(
    116,
    'Indoor Playground',
    'FerrisWheel',
    'I want to go to the indoor playground',
  ),
  placeCard(
    117,
    'Bounce House',
    'Zap',
    'I want to go to the bounce house place',
  ),
  placeCard(118, 'Autism Center', 'Heart', 'I want to go to the autism center'),
  placeCard(119, 'In the Car', 'Car', 'I want to stay in the car'),
  placeCard(
    120,
    'Resource Center',
    'Library',
    'I want to go to the resource center',
  ),
]
