import { card, PremadeCard } from './types'

/**
 * 135 pre-made vocabulary word cards with sensory descriptors.
 * Includes basic needs, emotions, physical needs, descriptors, time concepts,
 * social phrases, rejection phrases, sensory words, and regulation language for
 * individuals with autism.
 */
export const PREMADE_VOCAB_WORDS: PremadeCard[] = [
  // Basic needs & feelings
  card('vocab', 1, 'Yes', 'ThumbsUp', 'Yes'),
  card('vocab', 2, 'No', 'ThumbsDown', 'No'),
  card('vocab', 3, 'Please', 'HandHelping', 'Please'),
  card('vocab', 4, 'Thank You', 'Heart', 'Thank you'),
  card('vocab', 5, 'Sorry', 'Frown', 'I am sorry'),
  card('vocab', 6, 'Help', 'HandHelping', 'I need help'),
  card('vocab', 7, 'More', 'PlusIcon', 'I want more'),
  card('vocab', 8, 'All Done', 'CircleCheck', 'I am all done'),
  card('vocab', 9, 'Stop', 'Hand', 'Stop'),
  card('vocab', 10, 'Go', 'Zap', 'Go'),
  card('vocab', 11, 'Wait', 'Clock', 'Wait'),
  card('vocab', 12, 'My Turn', 'User', 'It is my turn'),
  card('vocab', 13, 'Your Turn', 'Users', 'It is your turn'),
  card('vocab', 14, 'I Want', 'Star', 'I want something'),
  card('vocab', 15, 'I Need', 'Star', 'I need something'),
  card('vocab', 16, 'I Like', 'ThumbsUp', 'I like that'),
  card('vocab', 17, "I Don't Like", 'ThumbsDown', 'I do not like that'),
  card('vocab', 18, 'I Love', 'Heart', 'I love that'),

  // Emotions
  card('vocab', 19, 'Happy', 'Smile', 'I feel happy'),
  card('vocab', 20, 'Sad', 'Frown', 'I feel sad'),
  card('vocab', 21, 'Angry', 'Angry', 'I feel angry'),
  card('vocab', 22, 'Scared', 'Eye', 'I feel scared'),
  card('vocab', 23, 'Worried', 'Meh', 'I feel worried'),
  card('vocab', 24, 'Tired', 'Moon', 'I feel tired'),
  card('vocab', 25, 'Sick', 'Thermometer', 'I feel sick'),
  card('vocab', 26, 'Hungry', 'Utensils', 'I am hungry'),
  card('vocab', 27, 'Thirsty', 'GlassWater', 'I am thirsty'),
  card('vocab', 28, 'Hot', 'Sun', 'I am hot'),
  card('vocab', 29, 'Cold', 'Snowflake', 'I am cold'),
  card('vocab', 30, 'Hurt', 'Syringe', 'Something hurts'),
  card('vocab', 31, 'Frustrated', 'Annoyed', 'I feel frustrated'),
  card('vocab', 32, 'Excited', 'Sparkles', 'I am excited'),
  card('vocab', 33, 'Bored', 'Meh', 'I am bored'),
  card('vocab', 34, 'Confused', 'CircleHelp', 'I am confused'),
  card('vocab', 35, 'Proud', 'Medal', 'I feel proud'),
  card('vocab', 36, 'Surprised', 'Sparkles', 'I am surprised'),
  card('vocab', 37, 'Calm', 'Leaf', 'I feel calm'),
  card('vocab', 38, 'Nervous', 'Zap', 'I feel nervous'),
  card('vocab', 39, 'Silly', 'Laugh', 'I feel silly'),
  card('vocab', 40, 'Loved', 'Heart', 'I feel loved'),

  // Physical needs
  card('vocab', 41, 'Bathroom', 'Bath', 'I need the bathroom'),
  card('vocab', 42, 'Drink', 'GlassWater', 'I want a drink'),
  card('vocab', 43, 'Eat', 'Utensils', 'I want to eat'),
  card('vocab', 44, 'Sleep', 'Moon', 'I want to sleep'),
  card('vocab', 45, 'Rest', 'Bed', 'I need to rest'),
  card('vocab', 46, 'Medicine', 'Pill', 'I need medicine'),
  card('vocab', 47, 'Hug', 'Heart', 'I want a hug'),
  card('vocab', 48, 'Break', 'Clock', 'I need a break'),
  card('vocab', 49, 'Outside', 'Sun', 'I want to go outside'),
  card('vocab', 50, 'Inside', 'Home', 'I want to go inside'),

  // Descriptors & directions
  card('vocab', 51, 'Big', 'Blocks', 'Big'),
  card('vocab', 52, 'Small', 'Blocks', 'Small'),
  card('vocab', 53, 'Up', 'Mountain', 'Up'),
  card('vocab', 54, 'Down', 'Waves', 'Down'),
  card('vocab', 55, 'In', 'Home', 'In'),
  card('vocab', 56, 'Out', 'Sun', 'Out'),
  card('vocab', 57, 'On', 'Lightbulb', 'On'),
  card('vocab', 58, 'Off', 'Moon', 'Off'),
  card('vocab', 59, 'Open', 'Book', 'Open'),
  card('vocab', 60, 'Close', 'Book', 'Close'),
  card('vocab', 61, 'Fast', 'Zap', 'Fast'),
  card('vocab', 62, 'Slow', 'Clock', 'Slow'),
  card('vocab', 63, 'Loud', 'Megaphone', 'Loud'),
  card('vocab', 64, 'Quiet', 'Bell', 'Quiet'),
  card('vocab', 65, 'Hot', 'Flame', 'Hot'),
  card('vocab', 66, 'Cold', 'Snowflake', 'Cold'),
  card('vocab', 67, 'Soft', 'Cloud', 'Soft'),
  card('vocab', 68, 'Hard', 'Blocks', 'Hard'),
  card('vocab', 69, 'Wet', 'Waves', 'Wet'),
  card('vocab', 70, 'Dry', 'Sun', 'Dry'),

  // Time
  card('vocab', 71, 'Now', 'Clock', 'Now'),
  card('vocab', 72, 'Later', 'Clock', 'Later'),
  card('vocab', 73, 'Today', 'Calendar', 'Today'),
  card('vocab', 74, 'Tomorrow', 'Calendar', 'Tomorrow'),
  card('vocab', 75, 'Yesterday', 'Calendar', 'Yesterday'),
  card('vocab', 76, 'Morning', 'Sunrise', 'Morning'),
  card('vocab', 77, 'Afternoon', 'Sun', 'Afternoon'),
  card('vocab', 78, 'Night', 'Moon', 'Night'),
  card('vocab', 79, 'Soon', 'Clock', 'Soon'),
  card('vocab', 80, 'Not Yet', 'Clock', 'Not yet'),

  // Social phrases
  card('vocab', 81, 'Hello', 'Smile', 'Hello'),
  card('vocab', 82, 'Goodbye', 'Hand', 'Goodbye'),
  card('vocab', 83, 'Good Morning', 'Sunrise', 'Good morning'),
  card('vocab', 84, 'Good Night', 'Moon', 'Good night'),
  card('vocab', 85, 'How Are You', 'Smile', 'How are you?'),
  card('vocab', 86, "I'm Okay", 'ThumbsUp', 'I am okay'),
  card('vocab', 87, 'Excuse Me', 'Hand', 'Excuse me'),
  card('vocab', 88, "I Don't Know", 'CircleHelp', 'I do not know'),
  card('vocab', 89, "I Don't Understand", 'CircleHelp', 'I do not understand'),
  card('vocab', 90, 'Say Again', 'Mic', 'Can you say that again?'),
  card('vocab', 91, 'Look', 'Eye', 'Look at this'),
  card('vocab', 92, 'Listen', 'Ear', 'Listen'),
  card('vocab', 93, 'Come Here', 'Hand', 'Come here'),
  card('vocab', 94, 'Go Away', 'Hand', 'Go away please'),
  card('vocab', 95, 'Play With Me', 'Users', 'Play with me'),
  card('vocab', 96, 'Leave Me Alone', 'User', 'Leave me alone please'),
  card('vocab', 97, "I'm Done", 'CircleCheck', 'I am done'),
  card('vocab', 98, 'Not Now', 'Clock', 'Not now'),
  card('vocab', 99, 'I Did It', 'Trophy', 'I did it!'),
  card('vocab', 100, 'Great Job', 'Star', 'Great job!'),
  // Additional vocabulary - rejection, sensory, regulation, and key phrases (101-135)
  card('vocab', 101, "Don't Want", 'ThumbsDown', 'I do not want that'),
  card('vocab', 102, 'Not That', 'ThumbsDown', 'Not that one'),
  card('vocab', 103, 'Different One', 'CircleHelp', 'I want a different one'),
  card('vocab', 104, 'Something Else', 'Star', 'I want something else'),
  card('vocab', 105, 'Too Bright', 'Sun', 'It is too bright'),
  card('vocab', 106, 'Too Loud', 'Megaphone', 'It is too loud'),
  card('vocab', 107, 'Itchy', 'Hand', 'It feels itchy'),
  card('vocab', 108, 'Uncomfortable', 'Frown', 'I feel uncomfortable'),
  card('vocab', 109, 'Feels Bad', 'Frown', 'This feels bad'),
  card('vocab', 110, 'Feels Good', 'Smile', 'This feels good'),
  card('vocab', 111, 'Show Me', 'Eye', 'Show me'),
  card('vocab', 112, 'Tell Me', 'Ear', 'Tell me'),
  card('vocab', 113, 'Help Me Find', 'Search', 'Help me find it'),
  card('vocab', 114, 'Where Is', 'MapPin', 'Where is it?'),
  card('vocab', 115, 'What Is That', 'CircleHelp', 'What is that?'),
  card('vocab', 116, 'First', 'CircleArrowUp', 'First'),
  card('vocab', 117, 'Then', 'CircleArrowRight', 'Then'),
  card('vocab', 118, 'Next', 'CircleArrowRight', 'Next'),
  card('vocab', 119, 'After', 'Clock', 'After'),
  card('vocab', 120, 'Before', 'Clock', 'Before'),
  card('vocab', 121, 'Finished', 'CircleCheck', 'Finished'),
  card('vocab', 122, 'This One', 'Hand', 'This one'),
  card('vocab', 123, 'That One', 'Hand', 'That one'),
  card('vocab', 124, 'Different', 'CircleHelp', 'Different'),
  card('vocab', 125, 'Same', 'CircleCheck', 'Same'),
  card('vocab', 126, 'Both', 'Users', 'Both'),
  card('vocab', 127, 'Tummy Hurts', 'Frown', 'My tummy hurts'),
  card('vocab', 128, 'Head Hurts', 'Frown', 'My head hurts'),
  card('vocab', 129, 'Ears Hurt', 'Ear', 'My ears hurt'),
  card('vocab', 130, 'Owie', 'Syringe', 'I have an owie'),
  card('vocab', 131, 'Need a Break', 'Clock', 'I need a break'),
  card('vocab', 132, 'Too Much', 'ThumbsDown', 'This is too much'),
  card('vocab', 133, 'Calm Down', 'Heart', 'I need to calm down'),
  card('vocab', 134, 'Deep Breaths', 'Wind', 'I need deep breaths'),
  card('vocab', 135, 'Not Fair', 'Frown', 'That is not fair'),
]
